import AppKit
import ApplicationServices
import Combine
import CoreGraphics
import Foundation
import Carbon.HIToolbox

public enum PasteOutcome: Equatable, Sendable {
    case ok
    case accessibilityDenied
    case pasteboardLocked
    case targetRejected
}

public protocol PasteActionPerforming {
    func performPaste() -> Bool
    func performPaste(targetPID: pid_t) -> Bool
}

public struct SystemPasteActionPerformer: PasteActionPerforming {
    public init() {}

    public func performPaste() -> Bool {
        if let pid = NSWorkspace.shared.frontmostApplication?.processIdentifier {
            return synthesizeCommandVPaste(to: pid)
        }
        return synthesizeCommandVPaste()
    }

    public func performPaste(targetPID: pid_t) -> Bool {
        synthesizeCommandVPaste(to: targetPID)
    }

    private func synthesizeCommandVPaste(to pid: pid_t) -> Bool {
        guard AXIsProcessTrusted() else { return false }

        guard let source = CGEventSource(stateID: .hidSystemState) else {
            return false
        }

        guard let keyDown = CGEvent(keyboardEventSource: source, virtualKey: CGKeyCode(kVK_ANSI_V), keyDown: true),
              let keyUp = CGEvent(keyboardEventSource: source, virtualKey: CGKeyCode(kVK_ANSI_V), keyDown: false) else {
            return false
        }

        keyDown.flags = .maskCommand
        keyUp.flags = .maskCommand
        keyDown.postToPid(pid)
        keyUp.postToPid(pid)
        return true
    }

    private func synthesizeCommandVPaste() -> Bool {
        guard AXIsProcessTrusted() else { return false }

        guard let source = CGEventSource(stateID: .hidSystemState) else {
            return false
        }

        guard let keyDown = CGEvent(keyboardEventSource: source, virtualKey: CGKeyCode(kVK_ANSI_V), keyDown: true),
              let keyUp = CGEvent(keyboardEventSource: source, virtualKey: CGKeyCode(kVK_ANSI_V), keyDown: false) else {
            return false
        }

        keyDown.flags = .maskCommand
        keyUp.flags = .maskCommand
        keyDown.post(tap: .cghidEventTap)
        keyUp.post(tap: .cghidEventTap)
        return true
    }
}

@MainActor
public final class PasteManager: ObservableObject {
    @Published public private(set) var stagedText: String = ""

    private let performer: any PasteActionPerforming
    private let pasteboard: NSPasteboard
    /// Accessibility-trust gate. Defaults to the live `AXIsProcessTrusted()` so
    /// production behavior is unchanged; injectable so tests can reach the paste
    /// success path (AX is never trusted in CI).
    private let accessibilityTrusted: () -> Bool
    /// Restore task from the most recent paste. Cancelled when a new paste starts
    /// so two pastes inside the `pasteRestoreDelay` window don't clobber each
    /// other's clipboard restore.
    private var restoreTask: Task<Void, Never>?

    public init(
        performer: any PasteActionPerforming = SystemPasteActionPerformer(),
        pasteboard: NSPasteboard = .general,
        accessibilityTrusted: @escaping () -> Bool = { AXIsProcessTrusted() }
    ) {
        self.performer = performer
        self.pasteboard = pasteboard
        self.accessibilityTrusted = accessibilityTrusted
    }

    public func stage(_ text: String) {
        stagedText = text
        pasteboard.clearContents()
        // Write the transcript as `.string` (mandatory so Cmd+V still pastes it)
        // plus the conventional clipboard-manager opt-out markers so well-behaved
        // history managers (Maccy, Paste, Raycast, …) skip the entry. Partial
        // mitigation only: Universal Clipboard has no public opt-out, so this does
        // not stop Continuity capture with certainty (see SEC-02).
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setString("1", forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))
        item.setString("1", forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
        item.setString("1", forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
        pasteboard.writeObjects([item])
    }

    public func stageText(_ text: String) {
        stage(text)
    }

    /// Put `text` on the clipboard as a plain string and stop — for the
    /// clipboard-only mode, where the user pastes it themselves. Unlike `stage`,
    /// this adds NO Transient/Concealed markers, so the entry stays visible to
    /// clipboard-history managers (which is what the user wants here). Synthesizes
    /// no Cmd+V, so it needs no Accessibility trust.
    public func copyOnly(_ text: String) {
        // This text now owns the clipboard: a restore still pending from an
        // earlier paste (a failed paste falls back to here) must not replace it.
        restoreTask?.cancel()
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
    }

    /// Synthesize the target app's own Undo (Cmd+Z) to reverse the last paste.
    /// Gated on Accessibility trust (posting synthetic key events requires it),
    /// posted directly to `targetPID` — the app the paste landed in.
    @discardableResult
    public func sendUndo(targetPID: pid_t) -> Bool {
        guard accessibilityTrusted() else { return false }
        guard let source = CGEventSource(stateID: .hidSystemState) else { return false }
        guard let keyDown = CGEvent(keyboardEventSource: source, virtualKey: CGKeyCode(kVK_ANSI_Z), keyDown: true),
              let keyUp = CGEvent(keyboardEventSource: source, virtualKey: CGKeyCode(kVK_ANSI_Z), keyDown: false) else {
            return false
        }
        keyDown.flags = .maskCommand
        keyUp.flags = .maskCommand
        keyDown.postToPid(targetPID)
        keyUp.postToPid(targetPID)
        return true
    }

    @discardableResult
    public func paste(_ text: String? = nil) -> PasteOutcome {
        guard accessibilityTrusted() else { return .accessibilityDenied }

        var saved: ClipboardSnapshot? = nil
        if let text {
            saved = captureClipboard()
            stage(text)
        }
        let stagedChangeCount = pasteboard.changeCount

        guard !stagedText.isEmpty else {
            return .targetRejected
        }

        let result = performer.performPaste()
        // Always restore: on success, after the target app has had time to
        // consume the staged text; on failure, immediately so the user's
        // prior clipboard isn't permanently overwritten.
        if let saved {
            scheduleClipboardRestore(saved, stagedChangeCount: stagedChangeCount,
                                     delay: result ? AppTimings.pasteRestoreDelay : 0.05)
        }
        return result ? .ok : .targetRejected
    }

    @discardableResult
    public func paste(_ text: String, targetPID: pid_t) -> PasteOutcome {
        guard accessibilityTrusted() else { return .accessibilityDenied }
        let saved = captureClipboard()
        stage(text)
        let stagedChangeCount = pasteboard.changeCount
        guard !stagedText.isEmpty else { return .targetRejected }
        let result = performer.performPaste(targetPID: targetPID)
        // Always restore: on success, after the target app has had time to
        // consume the staged text; on failure, immediately so the user's
        // prior clipboard isn't permanently overwritten.
        scheduleClipboardRestore(saved, stagedChangeCount: stagedChangeCount,
                                 delay: result ? AppTimings.pasteRestoreDelay : 0.05)
        return result ? .ok : .targetRejected
    }

    /// One entry per pasteboard item, each with every type that item carried.
    /// Kept per item so a multi-item clipboard (e.g. several files copied in
    /// Finder) is restored as the same items, not merged into a single one.
    private typealias ClipboardSnapshot = [[(NSPasteboard.PasteboardType, Data)]]

    private func captureClipboard() -> ClipboardSnapshot {
        guard let items = pasteboard.pasteboardItems else { return [] }
        return items.map { item in
            item.types.compactMap { type in
                item.data(forType: type).map { (type, $0) }
            }
        }.filter { !$0.isEmpty }
    }

    /// `stagedChangeCount` is the pasteboard's change count right after the
    /// transcript was staged. If it moved by restore time, something else
    /// (the user copying during the restore window) wrote the clipboard since —
    /// that newer content wins and the old snapshot is NOT put back over it.
    private func scheduleClipboardRestore(_ snapshot: ClipboardSnapshot,
                                          stagedChangeCount: Int,
                                          delay: TimeInterval) {
        restoreTask?.cancel()
        restoreTask = Task { @MainActor [weak self] in
            try? await Task.sleep(nanoseconds: UInt64(delay * 1_000_000_000))
            guard !Task.isCancelled, let self, !snapshot.isEmpty else { return }
            guard self.pasteboard.changeCount == stagedChangeCount else { return }
            self.pasteboard.clearContents()
            let items = snapshot.map { entries -> NSPasteboardItem in
                let item = NSPasteboardItem()
                for (type, data) in entries {
                    item.setData(data, forType: type)
                }
                return item
            }
            self.pasteboard.writeObjects(items)
        }
    }

    @discardableResult
    public func performPaste() -> PasteOutcome {
        paste()
    }

    public func clear() {
        stagedText = ""
    }

    public func clearStagedText() {
        clear()
    }
}
