#if canImport(Testing)
import Testing
@testable import JVoice

/// The SPEC for spoken-mathematics conversion — the Swift side of the Windows port's
/// `MathSpeechTests.cs`, case for case.
///
/// `converts` is what the feature must produce; `leavesAlone` is the half that matters
/// more — ordinary talking has to come back byte-identical. Both lists are the contract
/// every later change to `MathSymbols`, `SpokenNumbers` or `MathSpeech` has to keep green.
///
/// Since 2026-09-29 the expected OUTPUT follows the shared notation format
/// (`docs/math-notation-format.md`: "/" fractions, × vs juxtaposition, "sin θ"), so the
/// conversion cases no longer match the Windows `MathSpeechTests.cs` symbol for symbol until
/// the Windows engine mirrors the change (list in `docs/math-notation-progress.md`).

private let mathConverts: [(String, String)] = [
    // ── the ask ──
    ("a subscript n equals 1 plus 7n", "aₙ = 1 + 7n"),
    ("x subscript i plus 1", "xᵢ + 1"),
    ("a subscript b equals 2", "a_b = 2"),
    // ── powers & roots ──
    ("x squared plus y squared equals z squared", "x² + y² = z²"),
    ("x to the power of n", "xⁿ"),
    ("e to the power of x equals 2", "eˣ = 2"),
    ("x superscript 10", "x¹⁰"),
    ("the square root of 16 equals 4", "the √16 = 4"),
    ("the cube root of 27", "the ∛27"),
    ("the fourth root of 16", "the ∜16"),
    ("the nth root of x", "the ⁿ√x"),
    // ── arithmetic & relations ──
    ("two plus two equals four", "2 + 2 = 4"),
    ("x equals negative 5", "x = -5"),
    ("3 x squared minus 2 x plus 1 equals 0", "3x² - 2x + 1 = 0"),
    ("n is greater than 100", "n > 100"),
    ("x is greater than or equal to 5", "x ≥ 5"),
    ("twenty five divided by five equals five", "25 ÷ 5 = 5"),
    ("3 over 4 plus 1 over 4 equals 1", "3/4 + 1/4 = 1"),
    ("n factorial equals 120", "n! = 120"),
    // ── spoken numbers ──
    ("x equals twenty five", "x = 25"),
    ("three point one four times r squared", "3.14r²"),
    ("one half plus one quarter equals three quarters", "½ + ¼ = ¾"),
    ("x equals two thirds", "x = ⅔"),
    ("two million five hundred thousand divided by 2", "2500000 ÷ 2"),
    // ── implicit multiplication ──
    ("delta x equals 5", "Δx = 5"),  // capital Δ = "change in x" (math-context round 2)
    ("x y equals 12", "xy = 12"),
    ("f of x equals a x squared plus b x plus c", "f(x) = ax² + bx + c"),
    // ── greek, constants, sets ──
    ("alpha plus beta equals gamma", "α + β = γ"),
    ("theta equals 30 degrees", "θ = 30°"),
    ("pi times r squared", "πr²"),
    ("x is an element of the reals", "x ∈ ℝ"),
    // ── big operators, calculus ──
    ("the sum from n equals 1 to infinity of 1 over n squared", "the ∑ₙ₌₁^∞ 1/n²"),
    ("the integral from 0 to 1 of x squared dx", "the ∫₀¹ x² dx"),
    ("the derivative of y with respect to x", "the dy/dx"),
    ("the partial derivative of f with respect to x equals 0", "the ∂f/∂x = 0"),
    ("the limit as x approaches 0 of sine of x over x equals 1", "the lim_(x→0) (sin x)/x = 1"),
    // ── powers spoken the short way, logs, combinatorics ──
    ("e to the x plus 1", "eˣ + 1"),
    ("2 to the 10 equals 1024", "2¹⁰ = 1024"),
    ("log base 2 of x equals 5", "log₂x = 5"),
    ("n choose k equals 10", "C(n, k) = 10"),
    ("x equals the square root of 2", "x = √2"),
    ("the absolute value of x equals 5", "the |x| = 5"),
    ("the integral from 0 to the square root of 2 of x dx", "the ∫₀^(√2) x dx"),
    // ── textbook shapes ──
    ("the sum from i equals 1 to n of i equals n times n plus 1 over 2", "the ∑ᵢ₌₁ⁿ i = nn + 1/2"),
    ("sine squared theta plus cosine squared theta equals 1", "sin²θ + cos²θ = 1"),
    ("e to the power of i pi plus 1 equals 0", "e^(iπ) + 1 = 0"),
    ("the derivative of x cubed with respect to x equals 3 x squared", "the d(x³)/dx = 3x²"),
    ("open parenthesis a plus b close parenthesis squared equals a squared plus 2 a b plus b squared",
     "(a + b)² = a² + 2ab + b²"),
    ("x subscript 1 plus x subscript 2 equals 10", "x₁ + x₂ = 10"),
    // ── weak "i" ──
    ("the sum from i equals 1 to n of i squared converges", "the ∑ᵢ₌₁ⁿ i² converges"),
    ("i equals the square root of negative 1", "i = √-1"),
    // ── grouping & functions ──
    ("open parenthesis x plus 1 close parenthesis squared", "(x + 1)²"),
    ("f of x equals x squared", "f(x) = x²"),
    ("y equals cosine of theta", "y = cos θ"),
    // ── mathematics inside a sentence ──
    ("so basically x equals 5 and that's it", "so basically x = 5 and that's it"),
    ("the formula is a subscript n equals 2n, which is neat", "the formula is aₙ = 2n, which is neat"),
    ("x equals 5.", "x = 5."),
    // ── the 2026-08-30 batch ──
    ("3 times 4 equals 12", "3 × 4 = 12"),
    ("x equals 2 times y", "x = 2y"),
    ("a cross product b equals c", "a × b = c"),
    ("1 over 2 plus 1 over 3", "1/2 + 1/3"),
    ("22 over 7 is approximately pi", "22/7 ≈ π"),
    ("x over n equals 2", "x/n = 2"),
    ("x over y equals 2", "x/y = 2"),
    ("10 divided by 2 equals 5", "10 ÷ 2 = 5"),
    ("1 over n squared", "1/n²"),
    ("log base 2 of 8", "log₂8"),
    ("log base 10 of 1000 equals 3", "log₁₀1000 = 3"),
    ("log sub 2 of x", "log₂x"),
    ("so we take log base 2 of x and then move on", "so we take log₂x and then move on"),
    ("log base n of x equals 5", "logₙx = 5"),
    ("u n equals 1 plus 7n", "uₙ = 1 + 7n"),
    ("u 1 equals 70000", "u₁ = 70000"),
    ("u n plus 1 equals 2 u n", "uₙ + 1 = 2uₙ"),
    ("a n equals a 1 times r to the power of n", "aₙ = a₁rⁿ"),
    ("5000 parentheses open, 1 plus 1.03 over 100 parentheses close", "5000 (1 + 1.03/100)"),
    ("x equals open paren a plus b close paren times c", "x = (a + b)c"),
    // ── the 2026-09-23 package (bug-hunt fixes 1–6; diverges from Windows on grouping) ──
    ("x to the 3", "x³"),
    ("2 to the power of 10", "2¹⁰"),
    ("3 x 4 equals 12", "3 × 4 = 12"),
    ("26 x 26 x 26 equals 17,576", "26 × 26 × 26 = 17576"),
    ("the probability that X is less than or equal to 3 equals 0.65", "P(X ≤ 3) = 0.65"),
    ("1 over 52 choose 5", "1/C(52, 5)"),
    ("1 over n factorial", "1/n!"),
    ("n choose n minus k", "C(n, n - k)"),
    ("n plus k minus 1 choose k", "C(n + k - 1, k)"),
    ("n choose k equals n minus 1 choose k minus 1 plus n minus 1 choose k",
     "C(n, k) = C(n - 1, k - 1) + C(n - 1, k)"),
    ("10 times 9 times 8 over 3 times 2 times 1", "(10 × 9 × 8)/(3 × 2 × 1)"),
    ("n factorial over k factorial times n minus k factorial", "n!/(k!(n - k)!)"),
    ("the probability of A given B", "P(A ∣ B)"),
    ("P of X less than 3", "P(X < 3)"),
    ("f of n equals f of n minus 1 plus f of n minus 2", "f(n) = f(n - 1) + f(n - 2)"),
    ("10 to the fifth", "10⁵"),
    ("x to the third power", "x³"),
    ("x to the 3rd", "x³"),
    // ── the shared notation format (docs/math-notation-format.md §4, 2026-09-29) ──
    // "over" is a slash; a side holding a space/operator — or a juxtaposed denominator — is bracketed
    ("a plus b over 2", "a + b/2"),
    ("a plus b all over 2", "(a + b)/2"),
    ("pi over 6", "π/6"),
    ("a over b plus c over d", "a/b + c/d"),
    ("1 over x squared", "1/x²"),
    ("x squared minus 9 all over x minus 3", "(x² - 9)/(x - 3)"),
    ("12 over 2T equals 400", "12/(2T) = 400"),
    ("5 over 6 to the fourth", "(5/6)⁴"),
    ("1 minus the quantity 5 over 6 to the 4", "1 - (5/6)⁴"),
    // "times": × between numbers, juxtaposition between letter terms; · is the dot product
    ("a sub n equals a sub 1 plus n minus 1 times d", "aₙ = a₁ + (n - 1)d"),
    ("6 times 7 divided by 2", "6 × 7 ÷ 2"),
    ("x times 2 equals 10", "x × 2 = 10"),
    ("open paren x plus 1 close paren times 2 equals 4", "(x + 1) × 2 = 4"),
    ("26 choose 4 times 10 choose 3", "C(26, 4) × C(10, 3)"),
    ("the probability of B given A times the probability of A", "P(B ∣ A) × P(A)"),
    ("2 times sine x times cosine x equals 1", "2 sin x cos x = 1"),
    ("a dot b", "a · b"),
    // "divided by" is a fraction in algebra
    ("x divided by 2 y equals 1", "x/(2y) = 1"),
    ("x divided by y squared equals 1", "x/y² = 1"),
    // functions: brackets only for a multi-term argument; smallest reading unless "the quantity"
    ("sine squared theta", "sin²θ"),
    ("cosine 2 theta equals 1", "cos 2θ = 1"),
    ("sine of x plus 1 equals 2", "sin x + 1 = 2"),
    ("sine of the quantity x plus 1", "sin(x + 1)"),
    ("natural log of 2", "ln 2"),
    ("log base 3 of x plus 1", "log₃x + 1"),
    ("log base 3 of the quantity x plus 1", "log₃(x + 1)"),
    // roots: a radicand of more than one number/letter is bracketed
    ("the square root of 2 x equals 4", "the √(2x) = 4"),
    ("the square root of x plus 1", "the √x + 1"),
    ("the square root of the quantity b squared minus 4 a c", "the √(b² - 4ac)"),
    ("x equals negative b plus or minus the square root of the quantity b squared minus 4 a c all over 2 a",
     "x = (-b ± √(b² - 4ac))/(2a)"),
    // powers
    ("10 to the power of minus 3", "10⁻³"),
    ("e to the minus x squared", "e^(-x²)"),
    ("x to the quantity n plus 1", "xⁿ⁺¹"),
    // calculus & the rest
    ("d y by d x equals 3 x squared minus 4", "dy/dx = 3x² - 4"),
    ("d y d x", "dy/dx"),
    ("the double integral of f d y d x", "the ∬ f dy dx"),
    ("f prime of x equals 2 x plus 1", "f′(x) = 2x + 1"),
    ("f double prime of x equals 6 x", "f″(x) = 6x"),
    ("f inverse of x", "f⁻¹(x)"),
    ("5 factorial", "5!"),
    ("x tends to infinity", "x → ∞"),
    ("the limit as n tends to infinity of 1 over n equals 0", "the lim_(n→∞) 1/n = 0"),
    ("20 percent of 50 equals 10", "20% of 50 = 10"),
    ("angle A B C equals 90 degrees", "∠ABC = 90°"),
    // ── David's failed dictation, 2026-09-29: bare "root of", glued "Kx", "sigma of" ──
    ("K squared plus the root of K cubed times Kx squared sigma of 3.", "K² + √K³ × Kx² ∑ 3."),
    ("k squared plus the square root of k cubed times k x squared", "k² + √k³ × kx²"),
    ("x plus the root of 2", "x + √2"),
    ("the root of K cubed", "the √K³"),
    ("k squared times Kx squared", "k²Kx²"),
    // "sigma" is the SUM SIGN (David, 2026-09-29); the letter σ is "lowercase/small sigma"
    ("the sigma from i equals 1 to n of i", "the ∑ᵢ₌₁ⁿ i"),
    ("Sigma from k equals 0 to infinity of x to the k", "∑ₖ₌₀^∞ xᵏ"),
    ("small sigma equals 2", "σ = 2"),
    ("x equals lowercase sigma of 3", "x = σ(3)"),
    ("the limit as x approaches pi of sine x", "the lim_(x→π) sin x"),
    // ── explicit escape hatch ──
    ("start equation capital sigma end equation", "Σ"),
    ("write start equation alpha end equation here", "write α here"),
]

private let mathLeavesAlone: [String] = [
    "this is a subscript of the value",
    "the subscript was hard to read",
    "two times a day keeps the doctor away",
    "plus I think we should go now",
    "in less than a minute we were done",
    "he was over there by the tree",
    "let's go over the plan one more time",
    "she scored an A plus on the test",
    "sixty times better than before",
    "I have more than enough time",
    "I'm 100 percent sure about this",
    "it's 30 degrees outside today",
    "the sum of my fears is nothing",
    "we need to sum up the results",
    "an integral part of the plan",
    "root cause analysis takes time",
    "the square root of all evil",
    "the alpha version ships tomorrow",
    "God is the alpha and the omega",
    "the power of positive thinking",
    "a lot of people over the years",
    "one of them said something else",
    "I got 5 of 10 questions right",
    "go to the store and buy some milk",
    "listen to the alpha version tomorrow",
    "the base of the mountain was covered in snow",
    "I had to choose between the two options",
    "the highest you can look up is negative 90 degrees in minecraft",
    "let's say between 60 and negative 50 for now",
    "the ratio of boys to girls is 3 to 2",
    "I'll be there from 5 to 7 tomorrow",
    "the temperature dropped to minus 5 degrees",
    "we went over budget by a lot this quarter",
    "that is less than ideal for us",
    "x, y, and z are the variables",
    "f(x) = 3 is already written out",
    "three quarters of the class passed the test",
    "I ate half of the pizza and a hundred wings",
    "he said 50 plus i think it was more",
    "it was 3 because i wanted it",
    "so genesis one because i feel like it matters",
    "I woke up at seven and made coffee",
    "there were about a hundred people there",
    "give me a minute or two and I'll be ready",
    "he read chapter three verse sixteen out loud",
    "i think u n is fine the way it is",
    "we counted u 1 and u 2 by hand",
    "the log of the tree was rotten through",
    "we need to log in with the email first",
    "she went over to plan b 2 instead",
    // the 2026-09-23 package's leak fixes (bug-hunt fixes 1 and 7)
    "I gave 5 to the 3 kids",
    "compared 2019 to the 2020 season it was better",
    "it went from 1990 to the 2000s",
    "y is 5 more than x",
    "we got 20 more than 15 last year",
    "I'm bringing a plus one",
    "he's a plus one at the wedding",
    "the infection rate is 5 per 100,000",
    "about 3 per 1000 births",
    // the 2026-09-29 format's new words stay words in ordinary speech
    "it's a 2 by 2 factorial design",
    "a 2 factorial design with 3 levels",
    "so that's 7 factorial which is a lot",
    "the quantity of water was 5 liters",
    "the quantity 3 was wrong",
    "type 2 tends to 3 times more often",
    "plan B tends to 5 percent of cases",
    "she tends to 3 patients every morning",
    "it was all over the news",
    "there were 20 all over 5 states",
    "the natural log cabin",
    "the prime minister of 3 countries",
    "the inverse of 5 is hard to explain",
    "I'm 100 percent of the way there",
    "20 percent of 50 people said yes",
    "dx dy is a nice dance",
    "section d y and d x",
    "it went from 5 to the minus 3 degrees",
    // bare "root of", "sigma of" and two-letter words (2026-09-29 fix)
    "the root of the problem",
    "the root of 3 problems",
    "root of all evil",
    "root for the team",
    "the root of our 3 main problems is time",
    "sigma of 3 people",
    "six sigma of 3 teams",
    "Six Sigma",
    "sigma male",
    "that's so sigma",
    "he is a sigma male with 3 cars",
    "our six sigma training took 5 days",
    "Sigma is a fraternity",
    "it was 2 plus ok",
    "he got 5 plus TV",
    "5 plus me",
    "3 times is enough",
    "7 times or so",
    "we need 5 plus AI tools",
    "my PC squared",
    "Ok squared away",
]


@Test func convertsSpokenMathematics() {
    for (spoken, expected) in mathConverts {
        #expect(MathSpeech.convert(spoken) == expected, "\(spoken)")
    }
}

@Test func leavesOrdinarySpeechByteIdentical() {
    for prose in mathLeavesAlone {
        #expect(MathSpeech.convert(prose) == prose, "\(prose)")
    }
}

@Test func emptyAndBlankInputAreReturnedUnchanged() {
    #expect(MathSpeech.convert("") == "")
    #expect(MathSpeech.convert("   ") == "   ")
}

@Test func conversionIsIdempotent() {
    // Converting already-converted text must be a no-op — otherwise re-processing a
    // transcript (or a symbol that lexes back into a construct) could compound.
    for (spoken, _) in mathConverts {
        let once = MathSpeech.convert(spoken)
        #expect(MathSpeech.convert(once) == once, "\(spoken)")
    }
}

@Test func aRealParagraphConvertsOnlyItsMathematics() {
    let spoken = """
        okay so I was working through the homework and the first problem says find x where \
        x squared minus 5 x plus 6 equals 0, which factors into open parenthesis x minus 2 \
        close parenthesis times open parenthesis x minus 3 close parenthesis, so x equals 2 \
        or x equals 3, and honestly that took me way longer than it should have
        """
    let expected = """
        okay so I was working through the homework and the first problem says find x where \
        x² - 5x + 6 = 0, which factors into (x - 2)(x - 3), so x = 2 \
        or x = 3, and honestly that took me way longer than it should have
        """
    #expect(MathSpeech.convert(spoken) == expected)
}

@Test func aRealBibleStudyParagraphIsUntouched() {
    let spoken = """
        alright so for the Bible study tonight we are in John chapter 3 verse 16, for God so \
        loved the world that he gave his only begotten son, and I want to talk about what \
        that means for us today, because a lot of people read that verse a hundred times \
        and never actually stop to think about it
        """
    #expect(MathSpeech.convert(spoken) == spoken)
}

/// David's real 2026-09-21 dictation, the one that exposed the parity gap: the physics
/// converts and the thinking-out-loud around it does not.
@Test func davidsSuvatDictationConvertsOnlyItsEquations() {
    let spoken = "I'm going to think this out loud. So for the first person, the first "
        + "runner, that is going at 6 meters per second, to find the suvet, we're just "
        + "going to use S equals U plus V divided by 2 times T. Basically, since the "
        + "initial and final velocities are both 6, it would be 12 over 2T equals 400. "
        + "So 400 divided by 6 equals 66.66 recurring seconds, which then equals to T."
    let expected = "I'm going to think this out loud. So for the first person, the first "
        + "runner, that is going at 6 meters per second, to find the suvet, we're just "
        + "going to use S = U + V/2 × T. Basically, since the "
        + "initial and final velocities are both 6, it would be 12/(2T) = 400. "
        + "So 400 ÷ 6 = 66.66 recurring seconds, which then equals to T."
    #expect(MathSpeech.convert(spoken) == expected)
}

/// Dictation-level context (`MathContext`, 2026-10-04, docs/math-context-design.md): a Greek
/// name outside an equation becomes its letter only when the rest of the dictation is
/// mathematics or it sits in an anchor slot ("value of λ"), and no veto applies. Mirrors the
/// "a Greek name is decided by the whole dictation" section of scripts/run-logic-tests.sh.
private let contextPromotes: [(String, String)] = [
    ("find the value of lambda", "find the value of λ"),
    ("Solve for theta.", "Solve for θ."),
    ("Let lambda be 3.", "Let λ be 3."),
    ("Express your answer in terms of pi.", "Express your answer in terms of π."),
    ("Find the value of lambda. We know that 5 equals K and X equals 5.",
     "Find the value of λ. We know that 5 = K and X = 5."),
    ("Find lambda. Okay, never mind, I'll write it down later. Anyway, 5 equals K and X equals 5.",
     "Find λ. Okay, never mind, I'll write it down later. Anyway, 5 = K and X = 5."),
    ("The period is 2 pi, and x equals 3.", "The period is 2π, and x = 3."),
    ("Solve for theta in the interval from 0 to pi, where 2 x equals 1.",
     "Solve for θ in the interval from 0 to π, where 2x = 1."),
    ("Lambda is 5. Then x equals 2 lambda.", "λ is 5. Then x = 2λ."),
    ("x equals lamda", "x = λ"),
    ("the value of capital lambda", "the value of Λ"),
    ("lambda equals 5", "λ = 5"),
    // maths elsewhere, but this word is no letter
    ("Write a lambda function that returns x squared plus 1, and test it with x equals 5.",
     "Write a lambda function that returns x² + 1, and test it with x = 5."),
    ("I deployed it on AWS Lambda, and the cost is x equals 5 cents per call.",
     "I deployed it on AWS Lambda, and the cost is x = 5 cents per call."),
    ("Alpha decay reduces the mass number by 4, so A equals 238 minus 4.",
     "Alpha decay reduces the mass number by 4, so A = 238 - 4."),
    ("My Omega watch says 5 o'clock, and question 3 is x plus 2 equals 7.",
     "My Omega watch says 5 o'clock, and question 3 is x + 2 = 7."),
    ("The plan costs 2 plus 1 free months, theta.", "The plan costs 2 + 1 free months, theta."),
    ("I'm taking omega 3 and x equals 5.", "I'm taking omega 3 and x = 5."),
    ("We joined Lambda Chi Alpha, x equals 2.", "We joined Lambda Chi Alpha, x = 2."),
    ("That's a big delta, and x equals 5.", "That's a big delta, and x = 5."),
    ("we had pi on pi day, x equals 3", "we had pi on pi day, x = 3"),
    ("say \"lowercase sigma\", and x equals 5", "say \"lowercase sigma\", and x = 5"),
    // "pie": whisper's spelling of pi, only between a number and a single letter (run-only)
    ("C equals 2 pie r", "C = 2πr"),
    ("C equals 2 pie, r", "C = 2 pie, r"),
    ("x equals 2 pie a", "x = 2 pie a"),
]

private let contextLeavesAlone: [String] = [
    "lambda", "Lambda.", "theta", "pi", "lambda is 5",
    "Lambda, the pie is really tasty.",
    "Lambda. Anyway, the pie is really tasty, you should try it.",
    "Hey lambda, come here, good girl.",
    "I paid 5 for the pie and the lambda function costs 0.2 cents.",
    "Is it Lambda or Lamda? I can never remember the spelling.",
    "The lambda function costs 0.2 cents and runs 3 times a day.",
    "Lambda, theta, sigma, these are all just names of fraternities in the movies.",
    "My uncle wears an Omega watch and I take omega 3 every morning.",
    "I signed up to be a beta tester and the alpha release is out.",
    "Happy Pi Day, I'm getting a pie after school.",
    "solve for pi day",
    "2 pie r", "I ate 2 pie r slices", "I paid 5 pie I think", "a pie chart and 2 pies",
]

@Test func greekNamesAreDecidedByTheWholeDictation() {
    for (spoken, expected) in contextPromotes {
        #expect(MathSpeech.convert(spoken) == expected, "\(spoken)")
        #expect(MathSpeech.convert(expected) == expected, "idempotent: \(spoken)")
    }
    for prose in contextLeavesAlone {
        #expect(MathSpeech.convert(prose) == prose, "\(prose)")
    }
    // bare "delta" only as a term of a whisper-written equation with its own letter (round 3)
    #expect(MathContext.windowOnlyNames == ["delta"])
    for runOnly in ["sigma", "eta", "iota", "kappa", "nu", "xi", "omicron", "psi", "big delta"] {
        #expect(!MathContext.promotable.contains(runOnly), "\(runOnly) must stay run-only")
    }
}

/// The 2026-10-04 adversarial verify of context promotion: recall it found missing…
private let contextVerifyPromotes: [(String, String)] = [
    ("Alpha and beta are the roots of x squared minus 5 x plus 6 equals 0. Find alpha beta.",
     "α and β are the roots of x² - 5x + 6 = 0. Find αβ."),
    ("Find the value of lambda mu.",
     "Find the value of λμ."),
    ("The circumference is 2 pi r, and x equals 2.",
     "The circumference is 2πr, and x = 2."),
    ("The pressure is rho g h, where h equals 2.",
     "The pressure is ρgh, where h = 2."),
    ("The force is mu m g, where m equals 2.",
     "The force is μmg, where m = 2."),
    ("The answer is 2 pi radians. x equals 1.",
     "The answer is 2π radians. x = 1."),
    ("In hypothesis testing, the significance level is alpha, and x equals 2.",
     "In hypothesis testing, the significance level is α, and x = 2."),
    ("The ball is released at an angle alpha above the horizontal, and v x equals u cos alpha.",
     "The ball is released at an angle α above the horizontal, and vx = u cos α."),
    ("Watch out, omega is in radians per second, so v equals omega r.",
     "Watch out, ω is in radians per second, so v = ωr."),
    ("Find the value of lambda, Lambda is the wavelength, and v equals f lambda.",
     "Find the value of λ, Lambda is the wavelength, and v = fλ."),
    ("theta equals pie over 2, so x equals 3.",
     "θ = π/2, so x = 3."),
    ("Find all values of theta. sine 2 theta equals cos theta.",
     "Find all values of θ. sine 2 theta equals cos theta."),
    ("Find mu. x bar equals 3.",
     "Find μ. x̄ = 3."),
    ("Find theta. d y by d x equals 3.",
     "Find θ. dy/dx = 3."),
    ("A equals pie r squared",
     "A = πr²"),
    ("The period is 2 pie over omega.",
     "The period is 2π/ω."),
    ("Hence find lambda.",
     "Hence find λ."),
    ("Let lambda equal 3.",
     "Let λ equal 3."),
    ("Express lambda in terms of k.",
     "Express λ in terms of k."),
    ("The wavelength lambda is 500 nanometres.",
     "The wavelength λ is 500 nanometres."),
    ("Given that theta is acute, find tan theta.",
     "Given that θ is acute, find tan θ."),
    ("The sum is capital sigma.",
     "The sum is Σ."),
    ("The eigenvalues are lambda 1 and lambda 2, and A x equals lambda x.",
     "The eigenvalues are λ₁ and λ₂, and Ax = λx."),
    ("Solve for theta in the interval 0 to 2 pi.",
     "Solve for θ in the interval 0 to 2π."),
]

/// …and the bleeds it found: the Greek word stays (other maths converts as before).
private let contextVerifyNoBleed: [(String, String)] = [
    ("In terms of beta access, everyone on the waitlist gets in next week.",
     "In terms of beta access, everyone on the waitlist gets in next week."),
    ("Let beta be honest, it's not ready to ship.",
     "Let beta be honest, it's not ready to ship."),
    ("In terms of pi, I prefer apple over pumpkin.",
     "In terms of pi, I prefer apple over pumpkin."),
    ("What's the value of mu in your opinion, the Pokemon card?",
     "What's the value of mu in your opinion, the Pokemon card?"),
    ("In terms of alpha, it's done. Mu, the dog, is sleeping. Pi, the cat, is hungry.",
     "In terms of alpha, it's done. Mu, the dog, is sleeping. Pi, the cat, is hungry."),
    ("Let beta be 2 hours late, honestly.",
     "Let beta be 2 hours late, honestly."),
    ("Express yourself in terms of beta.",
     "Express yourself in terms of beta."),
    ("Use the value of beta from the survey.",
     "Use the value of beta from the survey."),
    ("We had 2 pie over at grandma's.",
     "We had 2 pie over at grandma's."),
    ("We raised venture capital beta round last week, and the x equals 5 bug is fixed.",
     "We raised venture capital beta round last week, and the x = 5 bug is fixed."),
    ("I work at capital alpha partners, and the n equals 3 issue is closed.",
     "I work at capital alpha partners, and the n = 3 issue is closed."),
    ("Press X plus Y, it's big alpha energy.",
     "Press X + Y, it's big alpha energy."),
    ("Big pi slice for me please, and the score was x equals 2.",
     "Big pi slice for me please, and the score was x = 2."),
    ("T minus 10 minutes until launch, and the game is still in beta.",
     "T - 10 minutes until launch, and the game is still in beta."),
    ("For the controller, press X plus Y to parry. Honestly the beta feels smoother than the alpha.",
     "For the controller, press X + Y to parry. Honestly the beta feels smoother than the alpha."),
    ("I need n plus 1 tickets because my cousin is coming too. Btw the beta for the climb is to stay left.",
     "I need n + 1 tickets because my cousin is coming too. Btw the beta for the climb is to stay left."),
    ("I finished question 4, x equals 3. Then I went to the gym and felt like an absolute alpha. Then mum made pie.",
     "I finished question 4, x = 3. Then I went to the gym and felt like an absolute alpha. Then mum made pie."),
    ("The lambda sensor in my car is broken, and x equals 5 on the error code.",
     "The lambda sensor in my car is broken, and x = 5 on the error code."),
    ("x equals 2. Alpha team, move out.",
     "x = 2. Alpha team, move out."),
    ("My call sign is alpha, and y equals 12.",
     "My call sign is alpha, and y = 12."),
    ("So x equals 5 on the form. And by the way, tau is a protein in the brain linked to Alzheimer's.",
     "So x = 5 on the form. And by the way, tau is a protein in the brain linked to Alzheimer's."),
    ("The stock beta is like 1.2, and x equals 5.",
     "The stock beta is like 1.2, and x = 5."),
    ("Theta is killing my options, and x equals 10 contracts.",
     "Theta is killing my options, and x = 10 contracts."),
    ("My username is capital omega 99, and k equals 2.",
     "My username is capital omega 99, and k = 2."),
    ("Hey, alpha team! x equals 5.",
     "Hey, alpha team! x = 5."),
    ("x equals 5. [beta] tag.",
     "x = 5. [beta] tag."),
    ("x equals 5. Alpha: the first letter.",
     "x = 5. Alpha: the first letter."),
    ("x equals 5. The cow says mu.",
     "x = 5. The cow says mu."),
    ("I think the omega is the last letter, x equals 1.",
     "I think the omega is the last letter, x = 1."),
    ("Room 1 alpha and room 2 alpha are booked, x equals 4.",
     "Room 1 alpha and room 2 alpha are booked, x = 4."),
    ("We need alpha 1 and alpha 2 builds by Friday, n equals 2.",
     "We need alpha 1 and alpha 2 builds by Friday, n = 2."),
    ("I take omega 3 and omega 6 supplements, x equals 2.",
     "I take omega 3 and omega 6 supplements, x = 2."),
]

@Test func greekNamesSurviveTheAdversarialVerify() {
    for (spoken, expected) in contextVerifyPromotes {
        #expect(MathSpeech.convert(spoken) == expected, "\(spoken)")
        #expect(MathSpeech.convert(expected) == expected, "idempotent: \(spoken)")
    }
    for (spoken, expected) in contextVerifyNoBleed {
        #expect(MathSpeech.convert(spoken) == expected, "\(spoken)")
    }
    for gone in ["big alpha", "big pi", "big omega"] {
        #expect(!MathContext.promotable.contains(gone), "\(gone) is English")
    }
}

/// Recall rework (2026-10-04, design §10): real wordings and equations whisper already wrote as
/// symbols — David's exact sentence first — and the everyday senses beside a written "=".
private let recallReworkPromotes: [(String, String)] = [
    ("Where's the lambda in this equation for x = 5?",
     "Where's the λ in this equation for x = 5?"),
    ("Where's the lambda in this equation for x equals 5?",
     "Where's the λ in this equation for x = 5?"),
    ("Can you find the lambda for this one where 5x + 7z = 5?",
     "Can you find the λ for this one where 5x + 7z = 5?"),
    ("So 3z = 5 - 3λ. Then the lambda goes into equation 1.",
     "So 3z = 5 - 3λ. Then the λ goes into equation 1."),
    ("I wrote y=mx+c. Now how do I get lambda?",
     "I wrote y=mx+c. Now how do I get λ?"),
    ("Where's the mu in F = ma?",
     "Where's the μ in F = ma?"),
    ("What's the theta when tan x = 1?",
     "What's the θ when tan x = 1?"),
    ("So y = 2 - lambda comma lambda comma 3 - lambda.",
     "So y = 2 - λ comma λ comma 3 - λ."),
    ("Then 2x = 5 - 2λ, and the lambda stays free.",
     "Then 2x = 5 - 2λ, and the λ stays free."),
    ("So my alpha is 4 and z = 5 ÷ x - 4.",
     "So my α is 4 and z = 5/x - 4."),
    ("So 0 = 0, which means infinite solutions, and the lambda can be anything.",
     "So 0 = 0, which means infinite solutions, and the λ can be anything."),
    ("So lambda's value is 3 and x = 2.",
     "So λ's value is 3 and x = 2."),
    ("So lambda² = 4 and x = 2.",
     "So λ² = 4 and x = 2."),
    ("What's lambda 1 if x = 5?",
     "What's λ₁ if x = 5?"),
    ("Is lambda 2 then? x² = 4.",
     "Is λ 2 then? x² = 4."),
    ("Is there a lambda such that 2x + y = 0?",
     "Is there a λ ∣ 2x + y = 0?"),
    ("Then delta x = 5, so x = 7.",
     "Then Δx = 5, so x = 7."),
    ("Q equals m c delta T",
     "Q = mcΔT"),
    ("The area is pi r² and r = 2.",
     "The area is πr² and r = 2."),
    ("Where's the Lambda in 3y + 3z = 5?",
     "Where's the λ in 3y + 3z = 5?"),
    ("What is lambda equal to when x = 2?",
     "What is λ equal to when x = 2?"),
]

private let recallReworkNoBleed: [String] = [
    "Set x = 5 in the config and the lambda function will pick it up.",
    "Use a lambda instead of a for loop, i = 0 to 10.",
    "1 + 1 = 2, everyone knows that, and the beta is out next week.",
    "2 + 2 = 4 and the alpha squad still lost.",
    "x = 5 on the error code, and the lambda sensor is broken.",
    "Set x = 5 and y = 10 in the config, then restart the beta server.",
    "Use a lambda for the sort key, like key=lambda x: x[1].",
    "Check if a == b before you deploy the alpha build.",
    "The beta is out, so download it now, and x = 2.",
    "We're still in beta, 500 users so far, and x = 2.",
    "x = 2. Pixel 9 beta has a new launcher.",
    "It's 1-0 and the alpha squad is winning.",
    "The deal was 2 + 1 at the Omega store.",
    "Set BETA=1 in the .env file.",
    "My Delta flight leaves at 5 and x = 2.",
    "Lambda, I don't know, the pie is really tasty.",
]

@Test func greekNamesFollowRealWordingsAndWrittenNotation() {
    for (spoken, expected) in recallReworkPromotes {
        #expect(MathSpeech.convert(spoken) == expected, "\(spoken)")
        #expect(MathSpeech.convert(expected) == expected, "idempotent: \(spoken)")
    }
    for prose in recallReworkNoBleed {
        #expect(MathSpeech.convert(prose) == prose, "\(prose)")
    }
}

// Fix round (2026-10-04): mirrors the "fix round" block of scripts/run-logic-tests.sh.
private let fixRoundPromotes: [(String, String)] = [
    ("So lambda = -3.",
     "So λ = -3."),
    ("So theta = 30°.",
     "So θ = 30°."),
    ("So theta = π/6.",
     "So θ = π/6."),
    ("So lambda = h/p.",
     "So λ = h/p."),
    ("So lambda = mg.",
     "So λ = mg."),
    ("So lambda = 2(x + 1).",
     "So λ = 2(x + 1)."),
    ("So phi = (1 + √5) ÷ 2.",
     "So φ = (1 + √5) ÷ 2."),
    ("Then alpha = 30° and beta = 60°.",
     "Then α = 30° and β = 60°."),
    ("So sin theta = 1/3.",
     "So sin θ = 1/3."),
    ("So lambda² = 4.",
     "So λ² = 4."),
    ("So lambda² - 4 = 0.",
     "So λ² - 4 = 0."),
    ("So x² + lambda² = 4.",
     "So x² + λ² = 4."),
    ("So x = -lambda + 2.",
     "So x = -λ + 2."),
    ("So a = -omega² x.",
     "So a = -ω²x."),
    ("So sin(theta) = 0.5.",
     "So sin(θ) = 0.5."),
    ("So y = A sin(omega t + phi), and phi = 0.",
     "So y = A sin(ωt + φ), and φ = 0."),
    ("So X ~ N(mu, sigma²), and mu = 50.",
     "So X ~ N(μ, sigma²), and μ = 50."),
    ("So det(A - lambda I) = 0.",
     "So det(A - λI) = 0."),
    ("So N = N0 e^(-lambda t).",
     "So N = N0 e^(-λt)."),
    ("So A = lambda N.",
     "So A = λN."),
    ("g equals G M over r squared",
     "g = GM/r²"),
    ("Where's the lambda in this equation for x equals to 5?",
     "Where's the λ in this equation for x = 5?"),
    ("So x equals to 3 - lambda.",
     "So x = 3 - λ."),
    ("Where's the lambda in this equation where x is 5?",
     "Where's the λ in this equation where x is 5?"),
    ("Where's this lambda coming from if x = 5?",
     "Where's this λ coming from if x = 5?"),
    ("Why is the lambda getting bigger when x = 5?",
     "Why is the λ getting bigger when x = 5?"),
    ("So the lambda disappears when x = 5.",
     "So the λ disappears when x = 5."),
    ("z is lambda and y is 2 minus lambda.",
     "z is λ and y is 2 - λ."),
    ("Find the values of lambda such that x² + lambda x + 4 = 0 has two roots.",
     "Find the values of λ such that x² + λx + 4 = 0 has two roots."),
    ("The area is pie r squared.",
     "The area is πr²."),
    ("The coefficient of friction mu is 0.3.",
     "The coefficient of friction μ is 0.3."),
    ("The angular speed omega is 2 rad/s.",
     "The angular speed ω is 2 rad/s."),
    ("The phase difference phi is 90°.",
     "The phase difference φ is 90°."),
    ("So A = pie r² and r = 3.",
     "So A = πr² and r = 3."),
    ("So delta E = mc².",
     "So ΔE = mc²."),
    ("So omega = delta theta over delta t.",
     "So ω = Δθ/Δt."),
    ("So the denominator 2 - lambda can't be zero.",
     "So the denominator 2 - λ can't be zero."),
    ("So lambda is 3 - x.",
     "So λ is 3 - x."),
    ("For which lambda does the system have no solutions?",
     "For which λ does the system have no solutions?"),
    ("For what values of lambda is the matrix singular?",
     "For what values of λ is the matrix singular?"),
    ("So tan theta = sin theta ÷ cos theta.",
     "So tan θ = sin θ ÷ cos θ."),
    ("So x equals 4 over 3 pi r cubed.",
     "So x = (4/3)πr³."),
    ("The volume of the sphere is 4 ÷ 3 pi r³.",
     "The volume of the sphere is (4/3)πr³."),
    ("So F = 1 over 4 pi epsilon naught.",
     "So F = 1/(4πε₀)."),
    ("So tau = r × F = 10 N m.",
     "So τ = r × F = 10 N m."),
    ("Epsilon = 12 V.",
     "ε = 12 V."),
    ("So the change in x is delta x = 5 m.",
     "So the change in x is Δx = 5 m."),
    ("So x = -2 lambda.",
     "So x = -2λ."),
    ("What is lambda in this equation?",
     "What is λ in this equation?"),
    ("What's the value of lambda?",
     "What's the value of λ?"),
    ("The value of lambda is 3.",
     "The value of λ is 3."),
    ("For a lambda of 2, x = 6.",
     "For a λ of 2, x = 6."),
    ("I have x = 5. Where's the lambda?",
     "I have x = 5. Where's the λ?"),
    ("Their omega is 2 and v = 6.",
     "Their ω is 2 and v = 6."),
    ("Can alpha be 4? Then z = 5 ÷ 0.",
     "Can α be 4? Then z = 5 ÷ 0."),
    ("The theta is the angle with the horizontal and v = 10.",
     "The θ is the angle with the horizontal and v = 10."),
    ("So if alpha equals to 4, then beta has to equal to 3 because 0 = β - 3.",
     "So if α = 4, then β has to equal to 3 because 0 = β - 3."),
    ("Theta = pie.",
     "θ = π."),
    ("I ate 3 pie r slices, x equals 2.",
     "I ate 3 pie r slices, x = 2."),
]

private let fixRoundNoBleed: [String] = [
    "Set x = 5 in the config. The lambda is still timing out though.",
    "The lambda is down again, I set n = 10 in the env.",
    "The lambda is called with n = 0 and throws.",
    "x = 2 and the theta is at 3.",
    "That lambda is the one that sends emails, and i = 0 is the counter.",
    "Our lambda is on Node 20 now and x = 3 works.",
    "Plan B = 20 euros, and the omega is too expensive.",
    "I tried n=100 and the lambda is still too slow.",
    "Tier list goes S > A > B and the omega is S tier.",
    "I ran 100m = 1 lap and the omega is on my wrist.",
    "x = 2 and his lambda is broken.",
    "x = 2 and my beta is ready.",
    "x = 2 and a lambda is broken.",
    "The lambda is down x = 2.",
    "The pi is down when x = 2.",
    "Set the alpha to 0.5 so the overlay is see-through x = 2.",
    "The alpha for x = 2 crashes.",
    "For beta, x = 2 is the limit.",
    "The equation x² = 4 has 2 solutions and the beta is finally out.",
    "The equation 3 + 4 = 7 is easy, the beta is out.",
    "x = 2. Omega is better than Rolex.",
    "Project lambda is late, x = 2.",
    "We called the server omega and x = 2.",
    "x = 2. Where's our omega?",
    "x = 2. He's alpha.",
    "x = 2. That's very beta of you.",
    "The latency is 50 μs and the mu is fine.",
    "alpha=1 and x = 2.",
    "Alpha² is a band, x = 2.",
    "The alpha's out and x = 2.",
    "x = 2. Fortnite went from alpha to beta in 2017.",
    "x = 2. Let beta be honest.",
    "Just let theta be, she's grumpy today, and x = 2.",
]

@Test func greekNamesFixRoundRecallWithoutBleeds() {
    for (spoken, expected) in fixRoundPromotes {
        #expect(MathSpeech.convert(spoken) == expected, "\(spoken)")
        #expect(MathSpeech.convert(expected) == expected, "idempotent: \(spoken)")
    }
    for prose in fixRoundNoBleed {
        #expect(MathSpeech.convert(prose) == prose, "\(prose)")
    }
}

/// Round 3 (docs/math-context-design.md §11): the P1–P7 families of the workflow-#2 final check.
private let roundThreePromotes: [(String, String)] = [
    ("Solve 2x + 3 = 7, also the lambda is in the denominator.",
     "Solve 2x + 3 = 7, also the λ is in the denominator."),
    ("x + y = 4, and the lambda is in the power.",
     "x + y = 4, and the λ is in the power."),
    ("Solve x + 4 = 9, also the theta is in the second quadrant.",
     "Solve x + 4 = 9, also the θ is in the second quadrant."),
    ("Solve for lambda: 3 lambda - 6 = 0.",
     "Solve for λ: 3λ - 6 = 0."),
    ("Solve for theta: 2 sin theta = 1.",
     "Solve for θ: 2 sin θ = 1."),
    ("Find lambda: lambda² = 9.",
     "Find λ: λ² = 9."),
    ("Solve for alpha: 2 alpha = 6.",
     "Solve for α: 2α = 6."),
    ("Is the lambda in this equation for x = 5 the same as before?",
     "Is the λ in this equation for x = 5 the same as before?"),
    ("The lambda in x + lambda = 5 is the same as before.",
     "The λ in x + λ = 5 is the same as before."),
    ("Find the value of mu such that the vectors are perpendicular.",
     "Find the value of μ such that the vectors are perpendicular."),
    ("Find the value of mu given that the block does not slide.",
     "Find the value of μ given that the block does not slide."),
    ("Okay so the beta here is the coefficient, y = 3 + beta x.",
     "Okay so the β here is the coefficient, y = 3 + βx."),
    ("So the alpha here is the angle, and sin alpha = 0.5.",
     "So the α here is the angle, and sin α = 0.5."),
    ("Right so the beta is basically the coefficient, y = beta x.",
     "Right so the β is basically the coefficient, y = βx."),
    ("Expand (x + lambda)^2.",
     "Expand (x + λ)^2."),
    ("(x + lambda)²",
     "(x + λ)²"),
    ("Theta = arctan(3/4).",
     "θ = arctan(3/4)."),
    ("|x - 2| < delta",
     "|x - 2| < δ"),
    ("x = pi/4",
     "x = π/4"),
    ("My answer is θ = pi/4",
     "My answer is θ = π/4"),
    ("Theta = sin⁻¹(0.6).",
     "θ = sin⁻¹(0.6)."),
    ("x = 3pi/2",
     "x = 3π/2"),
    ("The discriminant delta = b² - 4ac.",
     "The discriminant δ = b² - 4ac."),
    ("Factorise lambda² - 5 lambda + 6.",
     "Factorise λ² - 5λ + 6."),
    ("Theta is 30 degrees.",
     "θ is 30 degrees."),
    ("So the theta here is 30 degrees.",
     "So the θ here is 30 degrees."),
    ("the lambda is 600 nm",
     "the λ is 600 nm"),
    ("The theta we got was 0.93 rad.",
     "The θ we got was 0.93 rad."),
    ("Our alpha is 0.05, so we reject H0.",
     "Our α is 0.05, so we reject H0."),
    ("The mu of the distribution is 50 and sigma is 5.",
     "The μ of the distribution is 50 and sigma is 5."),
    ("Omega is 3 rad/s.",
     "ω is 3 rad/s."),
    ("The rho of water is 1000 kg/m³.",
     "The ρ of water is 1000 kg/m³."),
    ("Lambda is an eigenvalue of A.",
     "λ is an eigenvalue of A."),
    ("Multiply both sides by lambda.",
     "Multiply both sides by λ."),
    ("Divide by lambda.",
     "Divide by λ."),
    ("Now multiply by lambda and add 5x.",
     "Now multiply by λ and add 5x."),
    ("Is it theta or 2 theta in the double angle formula?",
     "Is it θ or 2θ in the double angle formula?"),
    ("Find mu such that the vectors are perpendicular.",
     "Find μ such that the vectors are perpendicular."),
    ("The gamma factor is 1.5.",
     "The γ factor is 1.5."),
    ("Then the delta x is 0.1.",
     "Then the Δx is 0.1."),
    ("Is mu the mean of the distribution?",
     "Is μ the mean of the distribution?"),
    ("The standard deviation is 3 and mu is 10.",
     "The standard deviation is 3 and μ is 10."),
]

private let roundThreeNoBleed: [String] = [
    "Solve 2x + 3 = 7, also the lambda is in the cloud.",
    "Solve x + 4 = 9, also the omega is in my bag.",
    "Solve 2x + 3 = 7, also lambda is in the cloud.",
    "Solve 2x = 10, also the lambda lives in the cloud.",
    "Find x if 2x + 3 = 7 by the way the omega is in the shop.",
    "Lambda function: it returns x + 1.",
    "Beta: the new build is out.",
    "Alpha: the first letter of the alphabet.",
    "Theta: my cat's name.",
    "Is the lambda in this region the same as before?",
    "Find a lambda such that the API returns 200.",
    "Is the beta the same as last week's build?",
    "Okay so the beta here is the new version, y = 3x + 2.",
    "Okay so the alpha here is the best one, and y = 3 + 2x.",
    "The lambda here is the function we deploy, x = 2.",
    "Lambda = arn of the function.",
    "Use the alpha/beta toggle in settings.",
    "We tag releases alpha/1 and beta/1.",
    "Ship the beta/2 build tonight.",
    "The beta is 30% off.",
    "The omega costs 5000 euros.",
    "The omega is 40 mm.",
    "Lambda 2 is 600 MB.",
    "The lambda is 512 MB.",
    "The lambda is 30 seconds.",
    "Beta is 30 degrees warmer today.",
    "The gamma is 2.2 on my monitor.",
    "Multiply your savings by beta.",
    "Divide the team by alpha and beta groups.",
    "The alpha factor is huge in this game.",
    "The gamma factor of my monitor is 2.2.",
    "Multiply by beta testers.",
    "The eigenvalue lecture was boring, and the beta is out.",
    "Pi is the best angle for photos.",
    "Let's integrate beta into the pipeline next sprint.",
    "Lambda is integral to our stack now.",
    "Lambda is the mean one of the bunch.",
    "Phi is the angle of my bed.",
    "Lambda adds a lot of friction to deploys.",
    "Squared, cubed, sine, cosine, theta, integral, derivative.",
]

@Test func greekNamesRoundThreeQuantitiesVocabularyAndPlaces() {
    for (spoken, expected) in roundThreePromotes {
        #expect(MathSpeech.convert(spoken) == expected, "\(spoken)")
        #expect(MathSpeech.convert(expected) == expected, "idempotent: \(spoken)")
    }
    for prose in roundThreeNoBleed {
        #expect(MathSpeech.convert(prose) == prose, "\(prose)")
    }
}

/// Round 3b (docs/math-context-design.md §12): the verify of round 3 — promote rows, and the partial
/// conversions bleed inputs keep (expected = what the engine wrote before context promotion).
private let roundThreeBPromotes: [(String, String)] = [
    ("Find alpha: 2 alpha = 6. Alpha: the team meets at 5.",
     "Find α: 2α = 6. Alpha: the team meets at 5."),
    ("Solve 3x - 1 = 8, also the lambda is in the second row.",
     "Solve 3x - 1 = 8, also the λ is in the second row."),
    ("Solve 3x + 4 = 10, also the lambda is in the parametric form.",
     "Solve 3x + 4 = 10, also the λ is in the parametric form."),
    ("Solve x + 1 = 3, and the epsilon is in the limit.",
     "Solve x + 1 = 3, and the ε is in the limit."),
    ("Solve 2x + 3 = 7, also the lambda is inside the square root.",
     "Solve 2x + 3 = 7, also the λ is inside the square root."),
    ("Solve 2x = 6, also the lambda is in the function.",
     "Solve 2x = 6, also the λ is in the function."),
    ("Solve 2x = 6, also the lambda is on the left hand side.",
     "Solve 2x = 6, also the λ is on the left hand side."),
    ("Solve 2x = 6, also the lambda is in the answer.",
     "Solve 2x = 6, also the λ is in the answer."),
    ("Solve 2x = 6, also the lambda is in the square root.",
     "Solve 2x = 6, also the λ is in the square root."),
    ("x + 2y = 6, and the lambda is in the first column.",
     "x + 2y = 6, and the λ is in the first column."),
    ("So 4x = 12, and the theta is in the range 0 to 360.",
     "So 4x = 12, and the θ is in the range 0 to 360."),
    ("y = 5 - x, also the lambda is on the right hand side.",
     "y = 5 - x, also the λ is on the right hand side."),
    ("Solve 2x + 1 = 9, and the beta is in the quadratic.",
     "Solve 2x + 1 = 9, and the β is in the quadratic."),
    ("y = x², and the theta is in the second quadrant here.",
     "y = x², and the θ is in the second quadrant here."),
    ("f = c/lambda",
     "f = c/λ"),
    ("E = hc/lambda",
     "E = hc/λ"),
    ("So E = hc/lambda.",
     "So E = hc/λ."),
    ("k = 2pi/lambda",
     "k = 2π/λ"),
    ("T = 2pi/omega",
     "T = 2π/ω"),
    ("omega = 2pi/T",
     "ω = 2π/T"),
    ("The period is 2pi/omega.",
     "The period is 2π/ω."),
    ("The lambda is 600 nm, so f = c/lambda.",
     "The λ is 600 nm, so f = c/λ."),
    ("f(x) = (x - alpha)(x - beta)",
     "f(x) = (x - α)(x - β)"),
    ("|lambda| < 1",
     "|λ| < 1"),
    ("Expand (lambda - 1)(lambda + 1).",
     "Expand (λ - 1)(λ + 1)."),
    ("Expand (alpha + beta)².",
     "Expand (α + β)²."),
    ("Simplify (lambda² - 1)/(lambda - 1).",
     "Simplify (λ² - 1)/(λ - 1)."),
    ("Simplify (theta + pi)/2.",
     "Simplify (θ + π)/2."),
    ("e^(-lambda t)",
     "e^(-λt)"),
    ("Solve for x in [0, 2pi].",
     "Solve for x in [0, 2π]."),
    ("So the omega, it's 2pi/T, so omega = 2pi/4.",
     "So the ω, it's 2π/T, so ω = 2π/4."),
    ("So the theta, which one is it, theta = 30° or theta = 150°?",
     "So the θ, which one is it, θ = 30° or θ = 150°?"),
    ("So does the theta cancel out in tan theta = sin theta / cos theta?",
     "So does the θ cancel out in tan θ = sin θ / cos θ?"),
    ("The epsilon is the error, |x - 1| < epsilon.",
     "The ε is the error, |x - 1| < ε."),
    ("So the delta is the discriminant, delta = b² - 4ac.",
     "So the δ is the discriminant, δ = b² - 4ac."),
    ("Solve for theta in [0, pi].",
     "Solve for θ in [0, π]."),
    ("Because 2 lambda = -4.",
     "Because 2λ = -4."),
    ("Wait is the lambda positive? Because 2 lambda = -4.",
     "Wait is the λ positive? Because 2λ = -4."),
    ("Since 3 theta = 90°.",
     "Since 3θ = 90°."),
    ("Because 2 lambda = 6°.",
     "Because 2λ = 6°."),
    ("I said theta = 35°.",
     "I said θ = 35°."),
    ("Then I said theta is acute, so theta = 35°.",
     "Then I said θ is acute, so θ = 35°."),
    ("Then I said theta is acute. So theta = 35°.",
     "Then I said θ is acute. So θ = 35°."),
    ("I think the alpha is wrong, it should be alpha = 30°.",
     "I think the α is wrong, it should be α = 30°."),
    ("The alpha is wrong, alpha = 30°.",
     "The α is wrong, α = 30°."),
    ("Find lambda such that the lines intersect.",
     "Find λ such that the lines intersect."),
    ("Find lambda such that the matrix has no inverse.",
     "Find λ such that the matrix has no inverse."),
    ("Find mu such that the system has infinitely many solutions.",
     "Find μ such that the system has infinitely many solutions."),
    ("Find mu given that the box doesn't move.",
     "Find μ given that the box doesn't move."),
    ("Find lambda given that the point lies on the line.",
     "Find λ given that the point lies on the line."),
    ("Is the lambda in the second equation the same as before?",
     "Is the λ in the second equation the same as before?"),
    ("Alpha is 0.05 so we reject the null.",
     "α is 0.05 so we reject the null."),
    ("At the 5% level alpha is 0.05.",
     "At the 5% level α is 0.05."),
    ("The mean mu is 12.",
     "The mean μ is 12."),
    ("Rho is 1.2 kg/m³ for air.",
     "ρ is 1.2 kg/m³ for air."),
    ("Okay so theta is 45 degrees here.",
     "Okay so θ is 45 degrees here."),
    ("Lambda is 600nm.",
     "λ is 600nm."),
    ("Omega is 5rad/s.",
     "ω is 5rad/s."),
    ("Rho is the density of the fluid.",
     "ρ is the density of the fluid."),
    ("Let theta be the angle at B.",
     "Let θ be the angle at B."),
    ("Let mu be the mean.",
     "Let μ be the mean."),
    ("Differentiate with respect to theta.",
     "Differentiate with respect to θ."),
    ("Integrate with respect to lambda.",
     "Integrate with respect to λ."),
    ("Plug lambda back into the first equation.",
     "Plug λ back into the first equation."),
    ("Substitute theta into the second equation.",
     "Substitute θ into the second equation."),
    ("Is it lambda or 2 lambda in the characteristic equation?",
     "Is it λ or 2λ in the characteristic equation?"),
    ("And then the lambda drops out when you subtract the two equations.",
     "And then the λ drops out when you subtract the two equations."),
    ("The lambda cancels when you divide both sides.",
     "The λ cancels when you divide both sides."),
    ("Okay so for lambda I got 3 and for mu I got -1.",
     "Okay so for λ I got 3 and for μ I got -1."),
    ("Find lambda such that the vectors are parallel.",
     "Find λ such that the vectors are parallel."),
    ("So E = hf and lambda = c/f, which gives E = hc/lambda.",
     "So E = hf and λ = c/f, which gives E = hc/λ."),
    ("v = f lambda, so f = v/lambda.",
     "v = fλ, so f = v/λ."),
    ("omega = 2pi/T, so T = 2pi/omega.",
     "ω = 2π/T, so T = 2π/ω."),
    ("The angular frequency is 2pi/omega.",
     "The angular frequency is 2π/ω."),
    ("g(x) = (x - lambda)(x + 3)",
     "g(x) = (x - λ)(x + 3)"),
    ("|mu| < 1",
     "|μ| < 1"),
    ("Expand (theta - 1)(theta + 2).",
     "Expand (θ - 1)(θ + 2)."),
    ("Simplify (mu + 1)/(mu - 1).",
     "Simplify (μ + 1)/(μ - 1)."),
    ("Solve for theta in [0, 2pi].",
     "Solve for θ in [0, 2π]."),
    ("So the mu, it's the coefficient, F = mu R.",
     "So the μ, it's the coefficient, F = μR."),
    ("The phi is the phase, y = sin(x + phi).",
     "The φ is the phase, y = sin(x + φ)."),
    ("Since 2 theta = 90°.",
     "Since 2θ = 90°."),
    ("Because 3 lambda = -6.",
     "Because 3λ = -6."),
    ("Rho is 1000 kg/m³ for water.",
     "ρ is 1000 kg/m³ for water."),
    ("So theta is 30 degrees here.",
     "So θ is 30 degrees here."),
    ("Lambda is 450nm.",
     "λ is 450nm."),
    ("Omega is 2rad/s.",
     "ω is 2rad/s."),
    ("Phi is the angle between the line and the plane.",
     "φ is the angle between the line and the plane."),
    ("Rho is the resistivity of the wire.",
     "ρ is the resistivity of the wire."),
    ("Let lambda be the wavelength.",
     "Let λ be the wavelength."),
    ("Let phi be the angle at C.",
     "Let φ be the angle at C."),
    ("Differentiate with respect to phi.",
     "Differentiate with respect to φ."),
    ("Substitute lambda into the second equation.",
     "Substitute λ into the second equation."),
    ("Plug mu back into the equation.",
     "Plug μ back into the equation."),
    ("Is it lambda or 3 lambda in the characteristic polynomial?",
     "Is it λ or 3λ in the characteristic polynomial?"),
    ("The mu cancels when you divide both sides.",
     "The μ cancels when you divide both sides."),
    ("Okay so for theta I got 30 and for phi I got 60.",
     "Okay so for θ I got 30 and for φ I got 60."),
    ("Solve 2x = 6, also the lambda is in the second column.",
     "Solve 2x = 6, also the λ is in the second column."),
    ("Solve 2x = 6, also the theta is in the third quadrant here.",
     "Solve 2x = 6, also the θ is in the third quadrant here."),
    ("Solve 2x = 6, also the lambda is under the square root.",
     "Solve 2x = 6, also the λ is under the square root."),
    ("Solve 2x = 6, and the lambda is in the answer.",
     "Solve 2x = 6, and the λ is in the answer."),
    ("Alpha is 0.01 so we reject the null.",
     "α is 0.01 so we reject the null."),
    ("At the 1% level alpha is 0.01.",
     "At the 1% level α is 0.01."),
    ("The mean mu is 7.",
     "The mean μ is 7."),
    ("The gamma factor is 2.",
     "The γ factor is 2."),
    ("The mu of the sample is 4.",
     "The μ of the sample is 4."),
    ("Lambda is an eigenvalue of B.",
     "λ is an eigenvalue of B."),
    ("Divide both sides by mu.",
     "Divide both sides by μ."),
    ("x + beta = 5, and the beta is 2 weeks away.",
     "x + β = 5, and the beta is 2 weeks away."),
    ("2 lambda = 6. The lambda is 30 seconds on cold start.",
     "2λ = 6. The lambda is 30 seconds on cold start."),
    ("lambda = 3. Lambda is 512 MB now.",
     "λ = 3. Lambda is 512 MB now."),
    ("3 omega = 9, omega is 40 mm, the small one.",
     "3ω = 9, omega is 40 mm, the small one."),
    ("theta = 2, and theta is 30 degrees warmer in Athens.",
     "θ = 2, and theta is 30 degrees warmer in Athens."),
    ("2 theta = 60, but the theta team is 3 days late.",
     "2θ = 60, but the theta team is 3 days late."),
]

/// Round 3b: the verify's bleed inputs and held-out everyday lines — byte for byte.
private let roundThreeBNoBleed: [String] = [
    "Theta is the slope at the ski resort.",
    "Omega is the slope for beginners, and it opens at 9.",
    "Lambda is the angle for this story.",
    "Omega is the multiplier for XP this weekend.",
    "Our omega is the multiplier for the bonus.",
    "The omega here is the angle for the campaign.",
    "Omega is the golden mean between price and quality.",
    "Theta is the coefficient for the bonus at work.",
    "Lambda is the parameter in the URL.",
    "Omega is the coefficient for the insurance.",
    "Lambda is the angle of the campaign.",
    "Beta is 38 degrees, he has a fever.",
    "Gamma is 38 degrees, call the doctor.",
    "Phi is 38 degrees and coughing.",
    "Theta is 25 degrees and sunny.",
    "The theta is 30 degrees and sunny.",
    "Our alpha is 200 degrees, put the pizza in.",
    "Lambda is 500 m, so we can walk.",
    "Lambda is 200 metres, then turn right.",
    "The lambda is 50 m, past the bank.",
    "Tau is 5 nm, lol.",
    "Park perpendicular to the curb, theta is right there.",
    "The quadratic was easy, so theta and I went to lunch.",
    "The discriminant question killed me, theta got it though.",
    "After radians, theta went home.",
    "Multiply both sides by 2, then omega is our next stop.",
    "Expected value aside, I think omega is overpriced.",
    "The expected value is low, so lambda is out.",
    "Angular momentum is on our side, lambda is winning.",
    "Both sides by now want omega gone.",
    "Null hypothesis this, null hypothesis that, omega needs a break.",
    "Double angle formulas are tough, and lambda is my study buddy.",
    "I'm a standard deviation above average, unlike omega.",
    "The phase difference between us and theta is huge.",
    "The alpha of the population is the leader.",
    "The alpha of the population of deer is old.",
    "The beta of the population survey is out.",
    "The mu of the population of wolves is weird.",
    "y = 2x + 1 is done, the omega is in the sample folder.",
    "I wrote x = 3, and the lambda is in the population centre.",
    "Divide it by omega, the new tier.",
    "Divide through by lambda, the new tier.",
    "Divide it by theta, the new tier.",
    "Divide it by omega and we're done with the split.",
    "Divide it by beta and alpha groups.",
    "The gamma factor is huge in this game.",
    "The gamma factor of my glasses is weird.",
    "Gamma factor is 2.2 by default.",
    "Our gamma factor is 2.4 in the video settings.",
    "Gamma factor matters for colour grading.",
    "Solve 2x + 3 = 7, also the lambda is in room 5.",
    "Solve 2x + 3 = 7, also the omega is in the system now.",
    "Check that x = 3 works, and the theta is at gate 12.",
    "Solve 2x + 3 = 7, also the omega is in aisle 7.",
    "Solve 2x + 3 = 7, and the lambda is on page 4 of the menu.",
    "Solve 3x = 9, the theta is in 2027 at the earliest.",
    "Solve 2x + 3 = 7, also the lambda is in the power bank.",
    "Solve 2x + 3 = 7, also the omega is in the graph database.",
    "Solve 2x + 3 = 7, also the theta is in the distribution list.",
    "Solve x - 1 = 4, and the theta is in the series.",
    "Solve 2x + 3 = 7, and the omega is in question now.",
    "x + β = 5, and the beta is 2 weeks away.",
    "Let β = 3. Also the beta is 50% off this week.",
    "π = 3.14 and the pi is 5 euros at the bakery.",
    "α = 0.05 so the alpha is 3 points ahead now.",
    "y = 2β + 1, and the beta is 30% off today.",
    "x + λ = 5, and the lambda is 30 seconds on cold start.",
    "x + β = 5, and the β is 2 weeks away.",
    "I ate pi/4 of the pizza.",
    "Pi/2 of the class failed.",
    "Beta, solve 2x + 3 = 7 first, then play.",
    "Lambda is the parameter we pass to the handler.",
    "Theta is the gradient on the bike route today.",
    "Mu is the mean girl from the show.",
    "Phi is the angle of her new haircut.",
    "Rho is the density of the crowd at the gig.",
    "Let theta be the one who decides.",
    "Let omega be the host tonight.",
    "Tau is 3 seconds behind us.",
    "Theta was 28 degrees, a lovely day in Athens.",
    "Omega is 30 degrees warmer than Oslo.",
    "Lambda is 600 m from the station, then turn left.",
    "The rho is 5 euros a slice.",
    "Our tau is 2 hours away.",
    "The phi is 40 minutes late.",
    "y = 3x and the omega is 50% off this week.",
    "Solve 2x = 4, also the lambda is 20 dollars a month.",
    "x = 2, and the theta is 3 points behind.",
    "Theta and I went to the cinema after the quadratic test.",
    "Me and lambda went to the matrix sequel.",
    "Between you and omega, the eigenvalue quiz was easy.",
    "Beta, finish your homework, x + 2 = 5 is easy.",
    "Alpha, come here, 2x = 4 is done.",
    "Pi, did you solve x = 3?",
    "Divide it by phi, the house rule.",
    "Divide everything by omega and the kids get the rest.",
    "Multiply it by lambda and we win the game.",
    "The gamma factor in this film is weird.",
    "The gamma factor is 2.2 for my TV.",
    "I ate pi/3 of the pie.",
    "Pi/4 of the cake is gone.",
    "The mu of the population is shrinking.",
    "The lambda of the sample team is happy.",
    "The sample of lambda users grew.",
    "Solve 2x + 3 = 7, also the lambda is in room 12.",
    "Solve 2x + 3 = 7, and the omega is on floor 3.",
    "Solve 2x + 3 = 7, also the theta is in the function room.",
    "Solve 2x + 3 = 7, also the lambda is in the answer key folder.",
    "Solve 2x = 6, then the phi is at the root bar.",
    "Solve 2x = 6, also the lambda is in the range rover.",
    "x = 2, and the lambda is in the series finale.",
    "x = 2, and the omega is in power now.",
    "Check that x = 3, the theta is in 2026 at the latest.",
    "Solve x = 4, and the lambda is on page 12.",
    "The double angle formula is hard, so lambda went home.",
    "The eigenvalue quiz is over, lambda is happy.",
    "Standard deviation aside, omega is winning.",
    "With respect to omega, the team did well.",
    "Both sides by Friday, lambda will send it.",
    "Null hypothesis or not, theta is coming tonight.",
    "I think the phase difference between me and theta is age.",
    "The two equations are boring, and omega is my favourite.",
    "After the two equations theta left.",
    "Find omega such that he is happy.",
    "Find lambda given that she left early.",
    "Find mu so that the party starts.",
    "Plug lambda back into the wall socket.",
    "Substitute theta into the team for the final.",
    "Differentiate yourself from omega and the rest.",
    "For lambda I got 3 presents.",
    "For omega we got 5 tickets, so we go.",
    "The mean mu is 12 years old.",
    "The mean lambda was rude.",
    "Okay so for theta I got a new bike.",
    "Lambda is 600nm wide on the chip.",
    "Omega is 5rad/s on the spec sheet, according to the watch site.",
    "Rho is 1.2 kg/m³ for air, my teacher said.",
    "Theta is 25 degrees here in Rome.",
    "The lambda function in 2x + 3 = 7 is cool.",
    "Is the lambda in our AWS account the same as before?",
    "y = 2x, and the theta is in the shop for repair.",
    "x = 2λ, and the lambda is on my wrist.",
    "x = 2ω, and the omega I bought is nice.",
    "3λ = 6, the lambda from AWS costs money.",
    "The ratio alpha/beta is fine.",
    "Ship w/beta tonight.",
    "Use my/lambda as the path.",
    "Check ui/lambda in the repo.",
]

@Test func greekNamesRoundThreeBVerifyFindings() {
    for (spoken, expected) in roundThreeBPromotes {
        #expect(MathSpeech.convert(spoken) == expected, "\(spoken)")
        #expect(MathSpeech.convert(expected) == expected, "idempotent: \(spoken)")
    }
    for prose in roundThreeBNoBleed {
        #expect(MathSpeech.convert(prose) == prose, "\(prose)")
    }
}

private let roundThreeBVerifyTwoPromotes: [(String, String)] = [
    ("Theta is 45 degrees.",
     "θ is 45 degrees."),
    ("So theta is 60 degrees, right?",
     "So θ is 60 degrees, right?"),
    ("The angle theta is 30 degrees.",
     "The angle θ is 30 degrees."),
    ("Phi is 90 degrees here.",
     "φ is 90 degrees here."),
    ("Lambda is 450 nm.",
     "λ is 450 nm."),
    ("The wavelength lambda is 500 nm, so f = c/lambda.",
     "The wavelength λ is 500 nm, so f = c/λ."),
    ("Omega is 4 rad/s.",
     "ω is 4 rad/s."),
    ("So omega is 2 radians per second.",
     "So ω is 2 radians per second."),
    ("Alpha is 0.01, so we reject H0.",
     "α is 0.01, so we reject H0."),
    ("Rho is 1000 kg/m³.",
     "ρ is 1000 kg/m³."),
    ("Lambda is an eigenvalue of the matrix.",
     "λ is an eigenvalue of the matrix."),
    ("Is lambda an eigenvalue of A?",
     "Is λ an eigenvalue of A?"),
    ("Multiply both sides by theta.",
     "Multiply both sides by θ."),
    ("Divide both sides by lambda.",
     "Divide both sides by λ."),
    ("Divide by mu.",
     "Divide by μ."),
    ("Then multiply by omega and subtract 3.",
     "Then multiply by ω and subtract 3."),
    ("Is it alpha or 2 alpha in the double angle formula?",
     "Is it α or 2α in the double angle formula?"),
    ("Find the value of lambda such that the vectors are parallel.",
     "Find the value of λ such that the vectors are parallel."),
    ("Find mu such that the lines intersect.",
     "Find μ such that the lines intersect."),
    ("Solve for theta: 2 cos theta = 1.",
     "Solve for θ: 2 cos θ = 1."),
    ("Solve for lambda: 2 lambda + 4 = 0.",
     "Solve for λ: 2λ + 4 = 0."),
    ("Okay so the alpha here is the angle, tan alpha = 3/4.",
     "Okay so the α here is the angle, tan α = 3/4."),
    ("So the beta here is the gradient, y = beta x + 2.",
     "So the β here is the gradient, y = βx + 2."),
    ("Theta is the angle between the two vectors.",
     "θ is the angle between the two vectors."),
    ("Mu is the mean of the distribution.",
     "μ is the mean of the distribution."),
    ("Lambda is the wavelength of the light.",
     "λ is the wavelength of the light."),
    ("Rho is the density of water.",
     "ρ is the density of water."),
    ("Let theta be the angle at A.",
     "Let θ be the angle at A."),
    ("Let lambda be the eigenvalue.",
     "Let λ be the eigenvalue."),
    ("Differentiate with respect to lambda.",
     "Differentiate with respect to λ."),
    ("Integrate with respect to theta.",
     "Integrate with respect to θ."),
    ("Substitute lambda into the first equation.",
     "Substitute λ into the first equation."),
    ("Plug theta back into the second equation.",
     "Plug θ back into the second equation."),
    ("omega = 2pi f",
     "ω = 2πf"),
    ("x = pi/6",
     "x = π/6"),
    ("theta = pi/3",
     "θ = π/3"),
    ("Expand (alpha + 2)².",
     "Expand (α + 2)²."),
    ("Expand (x - lambda)^2.",
     "Expand (x - λ)^2."),
    ("|x - 3| < delta",
     "|x - 3| < δ"),
    ("|x - a| < epsilon",
     "|x - a| < ε"),
    ("Theta = arctan(2/3).",
     "θ = arctan(2/3)."),
    ("Because 3 lambda = 9.",
     "Because 3λ = 9."),
    ("Since 2 theta = 60°.",
     "Since 2θ = 60°."),
    ("I said lambda = 4.",
     "I said λ = 4."),
    ("The lambda in 3x + lambda = 7 is the same as before.",
     "The λ in 3x + λ = 7 is the same as before."),
    ("Is the lambda in this equation for x = 2 the same as before?",
     "Is the λ in this equation for x = 2 the same as before?"),
    ("Solve 2x = 6, and the theta is in the second quadrant.",
     "Solve 2x = 6, and the θ is in the second quadrant."),
    ("Solve 2x = 6, and the lambda is on the right hand side.",
     "Solve 2x = 6, and the λ is on the right hand side."),
    ("The theta goes from 0 to 2pi.",
     "The θ goes from 0 to 2π."),
    ("Theta goes from 0 to pi.",
     "θ goes from 0 to π."),
    ("For lambda I got 3.",
     "For λ I got 3."),
    ("Okay so for lambda I got 2 and for mu I got 5.",
     "Okay so for λ I got 2 and for μ I got 5."),
    ("The gamma factor is 1.25.",
     "The γ factor is 1.25."),
    ("Then the delta x is 0.2.",
     "Then the Δx is 0.2."),
    ("The mean mu is 20.",
     "The mean μ is 20."),
    ("So alpha is 0.05 and we reject the null.",
     "So α is 0.05 and we reject the null."),
    ("The mu of the distribution is 10.",
     "The μ of the distribution is 10."),
    ("Expand (lambda + 1)(lambda - 2).",
     "Expand (λ + 1)(λ - 2)."),
    ("So the omega, it's 2pi/T, so omega = 2pi/3.",
     "So the ω, it's 2π/T, so ω = 2π/3."),
    ("The epsilon is the error, |x - 2| < epsilon.",
     "The ε is the error, |x - 2| < ε."),
    ("The angular velocity omega is 3 rad/s.",
     "The angular velocity ω is 3 rad/s."),
    ("Theta is 15 degrees, so sin theta = 0.26.",
     "θ is 15 degrees, so sin θ = 0.26."),
    ("Theta is 90 degrees.",
     "θ is 90 degrees."),
    ("The angle theta is 120 degrees here.",
     "The angle θ is 120 degrees here."),
    ("Phi is 0.5 rad.",
     "φ is 0.5 rad."),
    ("Lambda is 550 nm, so it's green.",
     "λ is 550 nm, so it's green."),
    ("Lambda is 2 m, so f = v/lambda.",
     "λ is 2 m, so f = v/λ."),
    ("Omega is 10 rad/s, so T = 2pi/omega.",
     "ω is 10 rad/s, so T = 2π/ω."),
    ("Alpha is 0.05 so we reject H0.",
     "α is 0.05 so we reject H0."),
    ("Mu is 0.4, the coefficient of friction.",
     "μ is 0.4, the coefficient of friction."),
    ("Lambda is the eigenvalue.",
     "λ is the eigenvalue."),
    ("Theta is the angle between the vectors.",
     "θ is the angle between the vectors."),
    ("Theta is the angle at C.",
     "θ is the angle at C."),
    ("Rho is the density of the gas.",
     "ρ is the density of the gas."),
    ("Let alpha be the angle at A.",
     "Let α be the angle at A."),
    ("Let omega be the angular velocity.",
     "Let ω be the angular velocity."),
    ("Multiply both sides by mu.",
     "Multiply both sides by μ."),
    ("Divide by theta.",
     "Divide by θ."),
    ("Divide both sides by omega and simplify.",
     "Divide both sides by ω and simplify."),
    ("The quadratic has roots alpha and beta.",
     "The quadratic has roots α and β."),
    ("The eigenvalues are lambda 1 and lambda 2.",
     "The eigenvalues are λ₁ and λ₂."),
    ("Find lambda such that the system has no solution.",
     "Find λ such that the system has no solution."),
    ("Find mu given that the vectors are perpendicular.",
     "Find μ given that the vectors are perpendicular."),
    ("Find the value of theta such that the area is maximum.",
     "Find the value of θ such that the area is maximum."),
    ("Differentiate with respect to omega.",
     "Differentiate with respect to ω."),
    ("Substitute mu into the second equation.",
     "Substitute μ into the second equation."),
    ("Plug lambda back into the equation.",
     "Plug λ back into the equation."),
    ("For mu I got 0.3.",
     "For μ I got 0.3."),
    ("Theta goes from 0 to 2pi.",
     "θ goes from 0 to 2π."),
    ("The theta runs from -pi to pi.",
     "The θ runs from -π to π."),
    ("Solve 2x = 6, also the lambda is in the numerator.",
     "Solve 2x = 6, also the λ is in the numerator."),
    ("Solve 2x = 6, and the theta is in the first quadrant.",
     "Solve 2x = 6, and the θ is in the first quadrant."),
    ("Solve 2x = 6, also the lambda is in the exponent.",
     "Solve 2x = 6, also the λ is in the exponent."),
    ("Solve 2x = 6, also the lambda is in the second row of the matrix.",
     "Solve 2x = 6, also the λ is in the second row of the matrix."),
    ("Solve for omega: 2 omega = 10.",
     "Solve for ω: 2ω = 10."),
    ("Solve for mu: mu + 3 = 7.",
     "Solve for μ: μ + 3 = 7."),
    ("So the lambda here is the gradient, y = lambda x + 1.",
     "So the λ here is the gradient, y = λx + 1."),
    ("The lambda in 2x + lambda = 9 is the same as before.",
     "The λ in 2x + λ = 9 is the same as before."),
    ("f = c/lambda, so lambda = c/f.",
     "f = c/λ, so λ = c/f."),
    ("v = omega r",
     "v = ωr"),
    ("a = omega² r",
     "a = ω²r"),
    ("E = hf = hc/lambda",
     "E = hf = hc/λ"),
    ("X ~ N(mu, 9) and P(X < 5) = 0.3.",
     "X ~ N(μ, 9) and P(X < 5) = 0.3."),
    ("|lambda| > 1",
     "|λ| > 1"),
    ("Expand (theta + 1)².",
     "Expand (θ + 1)²."),
    ("Simplify (alpha + beta)/2.",
     "Simplify (α + β)/2."),
    ("Since 2 lambda = 8, lambda = 4.",
     "Since 2λ = 8, λ = 4."),
    ("I got theta = 40°.",
     "I got θ = 40°."),
    ("So the theta here is 30 degrees, right?",
     "So the θ here is 30 degrees, right?"),
    ("The mean mu is 50.",
     "The mean μ is 50."),
    ("Then the delta t is 0.5 s.",
     "Then the Δt is 0.5 s."),
    ("In the double angle formula, is it alpha or 2 alpha?",
     "In the double angle formula, is it α or 2α?"),
    ("And the lambda drops out when we add the equations.",
     "And the λ drops out when we add the equations."),
    ("The theta cancels when you divide both sides by cos theta.",
     "The θ cancels when you divide both sides by cos θ."),
    ("So the lambda, which is the eigenvalue, satisfies det(A - lambda I) = 0.",
     "So the λ, which is the eigenvalue, satisfies det(A - λI) = 0."),
    ("Okay the theta, it's in the second quadrant, so cos theta < 0.",
     "Okay the θ, it's in the second quadrant, so cos θ < 0."),
    ("The mu here is the coefficient of friction, F = mu R.",
     "The μ here is the coefficient of friction, F = μR."),
    ("Find omega: omega² = 16.",
     "Find ω: ω² = 16."),
    ("Solve for phi: 2 sin phi = 1.",
     "Solve for φ: 2 sin φ = 1."),
    ("So the lambda is the wavelength and lambda = 500 nm.",
     "So the λ is the wavelength and λ = 500 nm."),
    ("What's the theta here? tan theta = 1.",
     "What's the θ here? tan θ = 1."),
    ("Is the lambda the same in both equations? 2x + lambda = 5 and x - lambda = 1.",
     "Is the λ the same in both equations? 2x + λ = 5 and x - λ = 1."),
    ("The epsilon here is small, |x| < epsilon.",
     "The ε here is small, |x| < ε."),
    ("Theta is acute, so theta = 30°.",
     "θ is acute, so θ = 30°."),
    ("Because the alpha is 30°, alpha = pi/6.",
     "Because the α is 30°, α = π/6."),
    ("The rho here is the density, rho = m/V.",
     "The ρ here is the density, ρ = m/V."),
    ("Lambda is 3, so 2 lambda = 6.",
     "λ is 3, so 2λ = 6."),
    ("The angle is pi/3.",
     "The angle is π/3."),
    ("So omega = 2pi/T and T = 4 s.",
     "So ω = 2π/T and T = 4 s."),
    ("The tau here is the torque, tau = rF.",
     "The τ here is the torque, τ = rF."),
    ("Then I differentiate with respect to theta.",
     "Then I differentiate with respect to θ."),
    ("The derivative with respect to lambda is 0.",
     "The derivative with respect to λ is 0."),
    ("Let phi be the phase angle.",
     "Let φ be the phase angle."),
    ("Let beta be the angle at B.",
     "Let β be the angle at B."),
]

private let roundThreeBVerifyTwoNoBleed: [String] = [
    "Phi is 39 degrees, poor thing.",
    "Beta is 38 degrees and still sleeping.",
    "Theta is 30 degrees warmer than Oslo.",
    "The theta is 20 degrees today.",
    "Alpha is 180 degrees in the oven now.",
    "Gamma is 37 degrees, she is fine.",
    "Lambda is 300 m from here, take the second left.",
    "The lambda is 2 km away.",
    "Lambda is 400 m down the road and then turn.",
    "Omega is 5 rad, the new energy drink.",
    "Tau is 3 nm, according to the spec sheet lol.",
    "Beta is the angle I want for the photo shoot.",
    "Theta is the slope of the roof at grandma's.",
    "Lambda is the parameter of the API call.",
    "Omega is the coefficient of the deal we signed.",
    "Phi is the angle of the camera in the hallway.",
    "Mu is the mean of the group, honestly.",
    "Alpha is the mean one in our class.",
    "Gamma is the multiplier for the loot drop.",
    "Theta is the gradient of the hill near our house.",
    "Let alpha be the team captain this year.",
    "Let omega be the default theme.",
    "Let theta be the angle you shoot from.",
    "Let mu be the moderator for today.",
    "Divide the pizza by omega and the kids.",
    "Multiply it by theta, the new hire.",
    "Divide everything by lambda, our biggest client.",
    "Multiply the budget by omega, the partner firm.",
    "Divide by omega, said the manager, then left.",
    "Theta went home after the eigenvalue quiz.",
    "The eigenvalue test was brutal, lambda cried.",
    "Perpendicular parking is hard, omega says.",
    "Standard deviation is boring, theta agrees.",
    "Omega and I did the double angle homework together.",
    "Lambda and me went to the expected value lecture.",
    "Me and theta studied the null hypothesis stuff.",
    "After the angular velocity lab, omega went to the gym.",
    "We talked about the characteristic equation and then lambda left.",
    "The phase difference lecture ran late so omega missed the bus.",
    "Lambda is in the system now.",
    "Omega is in the series finale.",
    "Theta is in the second row of the cinema.",
    "The lambda is in the first column of the spreadsheet.",
    "The omega is in the limit of my patience.",
    "Theta is in the function room downstairs.",
    "The lambda sits in the answer box at reception.",
    "Omega is on the right hand side of the stage.",
    "The omega is on the left hand side of the parking lot.",
    "Theta is in the range of the speakers.",
    "Lambda is in the quadratic building at uni.",
    "The theta is in the root folder.",
    "The lambda goes from 0 to 100 in 4 seconds.",
    "The omega runs from 9 to 5 on weekdays.",
    "Theta goes from 0 to 60 in 3 seconds.",
    "For omega I got 5 stars.",
    "For theta we got 3 tickets.",
    "For lambda I got 20 bucks.",
    "For lambda I got 2, and for omega I got 3, at the raffle.",
    "With respect to omega, I disagree.",
    "I did it with respect to lambda.",
    "Differentiate yourself with respect to theta.",
    "Substitute omega into the team.",
    "Plug the omega back into the charger.",
    "Find lambda such that he is happy.",
    "Find omega given that it's late.",
    "Find mu so that we can leave.",
    "Find theta such that the party starts.",
    "The mean mu is our cat.",
    "The alpha of the pack is huge.",
    "The beta of the stock is 1.2.",
    "The mu of the population sample survey is out.",
    "The sigma of the group is cool.",
    "Our alpha is 3 points ahead.",
    "The beta is 3 weeks late.",
    "The omega is 300 m water resistant.",
    "The gamma factor in the game is 2.2.",
    "The gamma factor is 2.2 in the settings.",
    "Beta is 30% off today.",
    "Alpha is 2 hours late.",
    "x = 2. Beta is 30% off.",
    "x = 2, and the beta is 50% off.",
    "I scored x = 5 on the quiz, and omega was in the shop.",
    "Solve 2x + 3 = 7, and then omega is the restaurant we go to.",
    "Solve 2x + 3 = 7, then theta and I went home.",
    "Solve 2x = 4, the omega is at the gym.",
    "Solve 2x = 4, also lambda is in my bag.",
    "Solve 2x = 4, the theta sits in the car.",
    "Solve 2x = 4, and the lambda is on the table in the kitchen.",
    "Solve 2x = 4, and the omega is in the box on the shelf.",
    "Solve 2x = 4, also the theta is in the group chat.",
    "Solve 2x = 4, the lambda is in the matrix sequel.",
    "Solve 2x = 4, the omega is in the circle of friends.",
    "Solve 2x = 4, the theta is in the identity folder.",
    "Solve 2x = 4, and the lambda is in the power struggle.",
    "Solve 2x = 4, the theta is in this term's play.",
    "Solve 2x = 4, the omega is in the vector file.",
    "Solve 2x = 4, the lambda is in room 12.",
    "Solve 2x = 4, and the lambda is in the 5 pm slot.",
    "I ate pi/2 of the cake.",
    "pi/4 of us came.",
    "The c/lambda thing is a meme.",
    "w/lambda we ship faster.",
    "Theta, solve this for me please.",
    "Beta, do 2x + 3 = 7 now.",
    "Alpha, finish x + 2 = 5 first.",
    "The quadratic was a breeze, then omega texted me.",
    "The discriminant was zero so lambda bought pizza.",
    "Expected value is a good movie, omega said.",
    "I bought the omega watch, it has a 38 mm case.",
    "He is a sigma, and the omega is in his bag.",
    "Lambda is 100 m from the station.",
    "Theta is 15 degrees, so bring a jacket.",
    "Theta is 15 degrees, so wear a coat and gloves.",
    "Phi was 40 degrees, so we went to the doctor.",
    "The omega is 4 rad, the new skate deck.",
    "Lambda is 600 nm, the new chip node.",
    "Rho is 1000 kg/m³ lol.",
    "Alpha is the angle we want for the selfie.",
    "Theta is the slope of the ski run.",
    "Lambda is the coefficient of our partnership.",
    "Omega is the parameter in our contract.",
    "Mu is the mean girl from the movie.",
    "Rho is the density of the traffic today.",
    "Phi is the frequency of our meetings.",
    "Let lambda be the host tonight.",
    "Let omega be the boss of this.",
    "Let theta be the angle of the story.",
    "Divide by omega and the other teams.",
    "Multiply by lambda, then call me.",
    "Divide the bill by theta and me.",
    "The quadratic was easy, then lambda texted me.",
    "The eigenvalue question was hard, but omega laughed.",
    "We did the double angle formula and omega bought pizza.",
    "The expected value of the bet was low so theta quit.",
    "Perpendicular lines are boring, omega says.",
    "Omega has the standard deviation slides from class.",
    "Lambda had the null hypothesis notes.",
    "I need the eigenvalue notes from lambda.",
    "Ask omega for the expected value worksheet.",
    "The angular velocity lab was fun and omega won.",
    "The lambda is in the server room.",
    "The omega is on the shelf in the kitchen.",
    "The theta is in the box under the bed.",
    "Solve 2x = 6, also the lambda is in the parking lot.",
    "Solve 2x = 6, also the omega is in the lobby now.",
    "Solve 2x = 6, and the theta is in the inbox.",
    "Solve 2x = 6, also the lambda is in the series on Netflix.",
    "Solve 2x = 6, also the omega is in the sum we owe.",
    "Solve 2x = 6, and the lambda is in the term paper.",
    "Solve 2x = 6, and the theta is at the root of the problem.",
    "Solve 2x = 6, the lambda is in the product launch.",
    "Solve 2x = 6, then omega is the venue.",
    "Solve 2x = 6, then lambda is the winner.",
    "Solve 2x = 6, and alpha, beta and gamma are the teams.",
    "Solve 2x = 6, then theta and omega are my friends.",
    "Solve 2x = 6, and omega is a cafe.",
    "x = 3, and lambda is our mascot.",
    "x = 3. Omega is the new place on Main Street.",
    "x = 3. Theta is a bakery.",
    "For omega we got 4 pizzas.",
    "For lambda I got 3 and it was cheap.",
    "For theta I got 5, the cheap one.",
    "Theta goes from 10 to 20 on Saturdays.",
    "The lambda runs from 0 to 100 percent.",
    "Omega goes from 9 to 5.",
    "Integrate with respect to omega's feelings.",
    "With respect to lambda, the boss is right.",
    "We were differentiating with respect to theta, our rival.",
    "Find omega such that we can talk.",
    "Find lambda given that it rained.",
    "Find mu so that you know.",
    "The mu of the population is unknown to me.",
    "The beta of the population is younger.",
    "The alpha of the sample is the loudest.",
    "Our omega is 300 euros.",
    "The beta is 5 dollars.",
    "The lambda is 3 hours away.",
    "Theta is 3 km away.",
    "x = 2, and the beta is 2 days late.",
    "λ = 2, and the lambda is 40 seconds long.",
    "θ = 30°, and the theta is 2 hours away.",
    "The gamma factor of this camera is 2.2.",
    "The gamma factor is great on this screen.",
    "The gamma factor in the shader is 2.2.",
    "c/lambda haha.",
    "2pi/omega is a cool band name.",
    "|lambda| is a cool logo.",
    "Beta, solve x + 2 = 5 then go to bed.",
    "Alpha, finish your homework, x = 3 is wrong.",
    "Lambda drops out of the race when you subtract the votes.",
    "Lambda cancels when it rains.",
    "Is omega an option for dinner?",
    "Is lambda a good name?",
    "Is theta an eigenvalue fan?",
    "The quadratic formula song is fun, theta sings it.",
    "X ~ N lol.",
    "Lambda ~ 5 people.",
    "Omega ~ 3 hours.",
    "So the lambda, which is my favourite bar, is closed.",
    "Okay the theta, it's in the second floor, my class.",
    "The mu here is the cutest cat.",
    "The omega here is the best watch, the 300 m one.",
    "Lambda is 3 blocks away, so we walk.",
    "Theta is acute, my friend says.",
    "Alpha is 30 now, so happy birthday.",
    "The rho here is the guy from the band.",
    "The tau here is the new teacher.",
    "Let phi be the one who decides.",
    "Let beta be the judge.",
    "The theta here is the vibe.",
    "The alpha here is the coach.",
    "So the beta here is the new version, y = 3x + 2.",
    "So the gamma here is the best player, x = 5.",
    "The omega here is the shop, x = 2.",
    "The lambda function is 30 lines, x = 3.",
    "Theta and I did the eigenvalue thing.",
    "Lambda and me went to the double angle lecture.",
    "x = 2, and theta is my brother.",
    "x = 2, and omega is a restaurant now.",
    "x = 2, then lambda is my best mate.",
    "Solve x + 1 = 2, but theta is busy.",
    "Divide it by 2, then omega is free.",
    "Multiply it by 3 and lambda pays.",
    "Omega is 30 degrees hotter in summer.",
    "Theta is 25 degrees warmer, lol.",
    "Beta was 39 degrees last night.",
    "Lambda is 600 m above sea level.",
    "Solve 2x + 3 = 7, also the omega sits in the sum we paid.",
    "The tau is 1 nm.",
    "Solve 2x + 3 = 7, then lambda, omega and theta are the groups.",
    "Theta is the eigenvalue joke from class, lol.",
    "Omega has the expected value I wanted from a watch shop.",
    "Lambda is 600 nm, lol, the shop.",
]

/// Round 3b, verify 2 (docs/math-context-design.md §12): held-out wordings written after the
/// rules — mirrored by scripts/run-logic-tests.sh.
@Test func greekNamesRoundThreeBHeldOutWordings() {
    for (spoken, expected) in roundThreeBVerifyTwoPromotes {
        #expect(MathSpeech.convert(spoken) == expected, "\(spoken)")
        #expect(MathSpeech.convert(expected) == expected, "idempotent: \(spoken)")
    }
    for prose in roundThreeBVerifyTwoNoBleed {
        #expect(MathSpeech.convert(prose) == prose, "\(prose)")
    }
}

@Test func scriptTablesArePaired() {
    // Every character that can be super/subscripted must have exactly one mapping.
    #expect(MathScript.superscript("2") == "²")
    #expect(MathScript.subscriptText("n") == "ₙ")
    #expect(MathScript.superscript("n+1") == "ⁿ⁺¹")
    #expect(MathScript.subscriptText("b") == nil)       // no Unicode subscript b
    #expect(MathScript.superscript("q") == nil)         // no Unicode superscript q
    #expect(MathScript.attach("x", "b", superscript: false) == "x_b")
    #expect(MathScript.attach("lim", "x→0", superscript: false) == "lim_(x→0)")
    #expect(MathScript.attach("e", "iπ", superscript: true) == "e^(iπ)")
}

@Test func vocabularyNeverShadowsAConstructTheEngineParses() {
    #expect(!MathSymbols.reservedPhrases.isEmpty)
    for reserved in MathSymbols.reservedPhrases {
        #expect(MathSymbols.phrases[reserved] == nil,
                "\(reserved) is parsed structurally by MathSpeech — it must not be a vocabulary key")
    }
}
#endif
