import AppKit
import Foundation

final class MockPasteActionPerformer: PasteActionPerforming {
    let result: Bool
    private(set) var callCount = 0

    init(result: Bool) {
        self.result = result
    }

    func performPaste() -> Bool {
        callCount += 1
        return result
    }

    func performPaste(targetPID: pid_t) -> Bool {
        callCount += 1
        return result
    }
}

#if canImport(Testing)
import Testing
@testable import JVoice

@Test
@MainActor
func stageWritesTextToPasteboard() {
    let pasteboard = NSPasteboard(name: NSPasteboard.Name("jvoice-test-\(UUID().uuidString)"))
    let performer = MockPasteActionPerformer(result: true)
    let manager = PasteManager(performer: performer, pasteboard: pasteboard)

    manager.stage("Hello, world!")

    #expect(manager.stagedText == "Hello, world!")
    // SEC-02: the staged item must still vend `.string` so Cmd+V works.
    #expect(pasteboard.string(forType: .string) == "Hello, world!")
    // SEC-02 markers present so well-behaved clipboard managers skip the entry.
    #expect(pasteboard.data(forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")) != nil)
    #expect(pasteboard.data(forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType")) != nil)
    #expect(pasteboard.data(forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")) != nil)
}

@Test
@MainActor
func stageOnGeneralPasteboardStillVendsString() {
    // Proves SEC-02 didn't break Cmd+V on the real general pasteboard.
    let pasteboard = NSPasteboard.general
    let saved = pasteboard.string(forType: .string)
    defer {
        pasteboard.clearContents()
        if let saved { pasteboard.setString(saved, forType: .string) }
    }
    let performer = MockPasteActionPerformer(result: true)
    let manager = PasteManager(performer: performer)

    manager.stage("Staged for Cmd+V")

    #expect(NSPasteboard.general.string(forType: .string) == "Staged for Cmd+V")
}

@Test
@MainActor
func pasteStagesTextAndInvokesPerformer() {
    let pasteboard = NSPasteboard(name: NSPasteboard.Name("jvoice-test-\(UUID().uuidString)"))
    let performer = MockPasteActionPerformer(result: true)
    let manager = PasteManager(performer: performer, pasteboard: pasteboard,
                               accessibilityTrusted: { true })

    let outcome = manager.paste("Paste me")

    #expect(outcome == .ok)
    #expect(manager.stagedText == "Paste me")
    #expect(pasteboard.string(forType: .string) == "Paste me")
    #expect(performer.callCount == 1)
}

@Test
@MainActor
func pasteDoesNothingWhenThereIsNoText() {
    let pasteboard = NSPasteboard(name: NSPasteboard.Name("jvoice-test-\(UUID().uuidString)"))
    let performer = MockPasteActionPerformer(result: true)
    // AX injected as trusted so the empty-staged-text branch is the one exercised.
    let manager = PasteManager(performer: performer, pasteboard: pasteboard,
                               accessibilityTrusted: { true })

    let outcome = manager.paste()

    #expect(outcome == .targetRejected)
    #expect(manager.stagedText.isEmpty)
    #expect(performer.callCount == 0)
}

@Test
@MainActor
func pasteDeniedWhenAccessibilityUntrusted() {
    let pasteboard = NSPasteboard(name: NSPasteboard.Name("jvoice-test-\(UUID().uuidString)"))
    let performer = MockPasteActionPerformer(result: true)
    let manager = PasteManager(performer: performer, pasteboard: pasteboard,
                               accessibilityTrusted: { false })

    #expect(manager.paste("Paste me") == .accessibilityDenied)
    #expect(manager.paste() == .accessibilityDenied)
    #expect(manager.paste("Paste me", targetPID: 0) == .accessibilityDenied)
    #expect(performer.callCount == 0)
}

@MainActor
@Test func failedPasteRestoresOriginalClipboard() async {
    let pasteboard = NSPasteboard.general
    pasteboard.clearContents()
    pasteboard.setString("ORIGINAL", forType: .string)

    let failingPerformer = MockPasteActionPerformer(result: false)
    let manager = PasteManager(performer: failingPerformer)
    let outcome = manager.paste("TRANSCRIPT", targetPID: 0)
    // AX-trusted in CI is unknowable: failingPerformer gives .targetRejected,
    // AX-denied short-circuits before clipboard capture.
    #expect(outcome == .targetRejected || outcome == .accessibilityDenied)

    // Wait past the 50ms restore delay + Task scheduling slack.
    try? await Task.sleep(nanoseconds: 600_000_000)

    let restored = pasteboard.string(forType: .string)
    #expect(restored == "ORIGINAL")
}

@MainActor
@Test func successfulPasteRestoresPriorClipboardAfterDelay() async {
    // Isolated named pasteboard: paste(_:targetPID:) captures/restores the
    // manager's injected pasteboard, so this is deterministic and side-effect-free.
    let pasteboard = NSPasteboard(name: NSPasteboard.Name("jvoice-test-\(UUID().uuidString)"))
    pasteboard.clearContents()
    pasteboard.setString("PRIOR", forType: .string)

    let performer = MockPasteActionPerformer(result: true)
    let manager = PasteManager(performer: performer, pasteboard: pasteboard,
                               accessibilityTrusted: { true })

    let outcome = manager.paste("TRANSCRIPT", targetPID: 0)
    #expect(outcome == .ok)
    #expect(performer.callCount == 1)
    // During the restore window the transcript is staged.
    #expect(pasteboard.string(forType: .string) == "TRANSCRIPT")

    // Wait past pasteRestoreDelay (0.30s) + Task scheduling slack.
    try? await Task.sleep(nanoseconds: 700_000_000)

    #expect(pasteboard.string(forType: .string) == "PRIOR")
}

@MainActor
@Test func secondPasteWithinRestoreWindowCoalescesRestore() async {
    // Two pastes inside the restore window: only the latest restore runs, and it
    // restores the clipboard captured before the *second* paste (the first
    // restore is cancelled, so the user's original is not clobbered back).
    let pasteboard = NSPasteboard(name: NSPasteboard.Name("jvoice-test-\(UUID().uuidString)"))
    pasteboard.clearContents()
    pasteboard.setString("FIRST", forType: .string)

    let performer = MockPasteActionPerformer(result: true)
    let manager = PasteManager(performer: performer, pasteboard: pasteboard,
                               accessibilityTrusted: { true })

    // First paste captures "FIRST" and stages "T1".
    #expect(manager.paste("T1", targetPID: 0) == .ok)
    #expect(pasteboard.string(forType: .string) == "T1")
    // Second paste (well within the 0.30s window) captures "T1" and stages "T2".
    #expect(manager.paste("T2", targetPID: 0) == .ok)
    #expect(pasteboard.string(forType: .string) == "T2")

    // Wait past pasteRestoreDelay + slack: only the second restore should run.
    try? await Task.sleep(nanoseconds: 700_000_000)

    // The first restore was cancelled (would have set "FIRST"); the surviving
    // restore writes the clipboard captured before the second paste ("T1").
    #expect(pasteboard.string(forType: .string) == "T1")
}

#elseif canImport(XCTest)
import XCTest
@testable import JVoice

@MainActor
final class PasteManagerTests: XCTestCase {
    func testStageWritesTextToPasteboard() {
        let pasteboard = NSPasteboard(name: NSPasteboard.Name("jvoice-test-\(UUID().uuidString)"))
        let performer = MockPasteActionPerformer(result: true)
        let manager = PasteManager(performer: performer, pasteboard: pasteboard)

        manager.stage("Hello, world!")

        XCTAssertEqual(manager.stagedText, "Hello, world!")
        // SEC-02: the staged item must still vend `.string` so Cmd+V works.
        XCTAssertEqual(pasteboard.string(forType: .string), "Hello, world!")
        // SEC-02 markers present so well-behaved clipboard managers skip the entry.
        XCTAssertNotNil(pasteboard.data(forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")))
        XCTAssertNotNil(pasteboard.data(forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType")))
        XCTAssertNotNil(pasteboard.data(forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")))
    }

    func testStageOnGeneralPasteboardStillVendsString() {
        let pasteboard = NSPasteboard.general
        let saved = pasteboard.string(forType: .string)
        defer {
            pasteboard.clearContents()
            if let saved { pasteboard.setString(saved, forType: .string) }
        }
        let performer = MockPasteActionPerformer(result: true)
        let manager = PasteManager(performer: performer)

        manager.stage("Staged for Cmd+V")

        XCTAssertEqual(NSPasteboard.general.string(forType: .string), "Staged for Cmd+V")
    }

    func testPasteStagesTextAndInvokesPerformer() {
        let pasteboard = NSPasteboard(name: NSPasteboard.Name("jvoice-test-\(UUID().uuidString)"))
        let performer = MockPasteActionPerformer(result: true)
        let manager = PasteManager(performer: performer, pasteboard: pasteboard,
                                   accessibilityTrusted: { true })

        let outcome = manager.paste("Paste me")

        XCTAssertEqual(outcome, .ok)
        XCTAssertEqual(manager.stagedText, "Paste me")
        XCTAssertEqual(pasteboard.string(forType: .string), "Paste me")
        XCTAssertEqual(performer.callCount, 1)
    }

    func testPasteDoesNothingWhenThereIsNoText() {
        let pasteboard = NSPasteboard(name: NSPasteboard.Name("jvoice-test-\(UUID().uuidString)"))
        let performer = MockPasteActionPerformer(result: true)
        let manager = PasteManager(performer: performer, pasteboard: pasteboard,
                                   accessibilityTrusted: { true })

        let outcome = manager.paste()

        XCTAssertEqual(outcome, .targetRejected)
        XCTAssertTrue(manager.stagedText.isEmpty)
        XCTAssertEqual(performer.callCount, 0)
    }

    func testPasteDeniedWhenAccessibilityUntrusted() {
        let pasteboard = NSPasteboard(name: NSPasteboard.Name("jvoice-test-\(UUID().uuidString)"))
        let performer = MockPasteActionPerformer(result: true)
        let manager = PasteManager(performer: performer, pasteboard: pasteboard,
                                   accessibilityTrusted: { false })

        XCTAssertEqual(manager.paste("Paste me"), .accessibilityDenied)
        XCTAssertEqual(manager.paste(), .accessibilityDenied)
        XCTAssertEqual(manager.paste("Paste me", targetPID: 0), .accessibilityDenied)
        XCTAssertEqual(performer.callCount, 0)
    }

    func testFailedPasteRestoresOriginalClipboard() async {
        let pasteboard = NSPasteboard(name: NSPasteboard.Name("jvoice-test-\(UUID().uuidString)"))
        pasteboard.clearContents()
        pasteboard.setString("ORIGINAL", forType: .string)

        let failingPerformer = MockPasteActionPerformer(result: false)
        let manager = PasteManager(performer: failingPerformer, pasteboard: pasteboard,
                                   accessibilityTrusted: { true })
        XCTAssertEqual(manager.paste("TRANSCRIPT", targetPID: 0), .targetRejected)

        try? await Task.sleep(nanoseconds: 600_000_000)

        XCTAssertEqual(pasteboard.string(forType: .string), "ORIGINAL")
    }

    func testSuccessfulPasteRestoresPriorClipboardAfterDelay() async {
        let pasteboard = NSPasteboard(name: NSPasteboard.Name("jvoice-test-\(UUID().uuidString)"))
        pasteboard.clearContents()
        pasteboard.setString("PRIOR", forType: .string)

        let performer = MockPasteActionPerformer(result: true)
        let manager = PasteManager(performer: performer, pasteboard: pasteboard,
                                   accessibilityTrusted: { true })

        XCTAssertEqual(manager.paste("TRANSCRIPT", targetPID: 0), .ok)
        XCTAssertEqual(performer.callCount, 1)
        XCTAssertEqual(pasteboard.string(forType: .string), "TRANSCRIPT")

        try? await Task.sleep(nanoseconds: 700_000_000)

        XCTAssertEqual(pasteboard.string(forType: .string), "PRIOR")
    }

    func testSecondPasteWithinRestoreWindowCoalescesRestore() async {
        let pasteboard = NSPasteboard(name: NSPasteboard.Name("jvoice-test-\(UUID().uuidString)"))
        pasteboard.clearContents()
        pasteboard.setString("FIRST", forType: .string)

        let performer = MockPasteActionPerformer(result: true)
        let manager = PasteManager(performer: performer, pasteboard: pasteboard,
                                   accessibilityTrusted: { true })

        XCTAssertEqual(manager.paste("T1", targetPID: 0), .ok)
        XCTAssertEqual(pasteboard.string(forType: .string), "T1")
        XCTAssertEqual(manager.paste("T2", targetPID: 0), .ok)
        XCTAssertEqual(pasteboard.string(forType: .string), "T2")

        try? await Task.sleep(nanoseconds: 700_000_000)

        // First restore cancelled (would set "FIRST"); surviving restore sets "T1".
        XCTAssertEqual(pasteboard.string(forType: .string), "T1")
    }
}

#else
@testable import JVoice

@MainActor
struct PasteManagerTestsFallback {
    static func run() {
        let pasteboard = NSPasteboard(name: NSPasteboard.Name("jvoice-test-\(UUID().uuidString)"))
        let performer = MockPasteActionPerformer(result: true)
        let manager = PasteManager(performer: performer, pasteboard: pasteboard,
                                   accessibilityTrusted: { true })

        manager.stage("Hello, world!")
        assert(manager.stagedText == "Hello, world!")
        assert(pasteboard.string(forType: .string) == "Hello, world!")
        assert(pasteboard.data(forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")) != nil)

        let outcome = manager.paste("Paste me")
        assert(outcome == .ok)
        assert(manager.stagedText == "Paste me")
        assert(pasteboard.string(forType: .string) == "Paste me")
        assert(performer.callCount == 1)

        let emptyManager = PasteManager(performer: performer, pasteboard: pasteboard,
                                        accessibilityTrusted: { true })
        let emptyOutcome = emptyManager.paste()
        assert(emptyOutcome == .targetRejected)
        assert(emptyManager.stagedText.isEmpty)

        let deniedManager = PasteManager(performer: performer, pasteboard: pasteboard,
                                         accessibilityTrusted: { false })
        assert(deniedManager.paste("Paste me") == .accessibilityDenied)
    }
}
#endif